import json
batch15 = {
  "mini-ex_Riggs Ford_eng": [
    {"title": "Mini Excavator Rental Riggs Ford TX — $200/Day Delivered", "description": "Compact excavator for rent near Riggs Ford TX. Delivered to your job site.\n\nGreat for trenching, grading, utility lines, stump removal, and land clearing.\n\n$200/day. Delivery to Riggs Ford: $242.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Riggs Ford TX — Delivery Available", "description": "Kubota compact excavator available for Riggs Ford TX. We haul it to your site.\n\n$200/day + $242.20 delivery to Riggs Ford.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Riggs Ford TX Excavator Rental — Trenching & Land Clearing", "description": "Compact excavator rental in Riggs Ford TX. Handles rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $242.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Riggs Ford TX — $200/Day", "description": "Kubota compact excavator rental serving Riggs Ford TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $242.20.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Riggs Ford TX — $200/Day Delivered to Site", "description": "Compact excavator available for Riggs Ford TX and surrounding areas.\n\n$200/day + $242.20 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Riggs Ford_eng": [
    {"title": "Track Loader Rental Riggs Ford TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Riggs Ford TX.\n\nIdeal for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Riggs Ford: $242.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Riggs Ford TX — Rent Daily", "description": "Kubota SVL75-2 track loader rental in Riggs Ford TX. More traction than wheeled skid steers on rough terrain.\n\n$300/day. Riggs Ford delivery: $242.20.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Riggs Ford TX — $300/Day", "description": "Need a track loader near Riggs Ford? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $242.20 delivery to Riggs Ford.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Riggs Ford TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Riggs Ford TX. Handles tough terrain and heavy loads.\n\nDaily rate: $300. Delivery: $242.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Riggs Ford TX — Delivered to Site", "description": "Compact track loader rental serving Riggs Ford TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $242.20.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Hubbard_eng": [
    {"title": "Mini Excavator Rental Hubbard TX — $200/Day Delivered", "description": "Compact excavator for rent in Hubbard TX. Delivered to your job site in Hill County.\n\nPerfect for trenching, grading, drainage, stump removal, and land clearing.\n\n$200/day. Delivery to Hubbard: $242.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent in Hubbard TX — Delivery Available", "description": "Need a compact excavator in Hubbard? We bring the machine to you.\n\n$200/day + $242.20 delivery to Hubbard.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Hubbard TX Excavator Rental — Trenching, Grading & Clearing", "description": "Compact excavator rental serving Hubbard TX. Ideal for rural properties, utility lines, and construction prep.\n\n$200/day. Delivery: $242.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Hubbard TX — $200/Day", "description": "Kubota compact excavator rental in Hubbard TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $242.20.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Hubbard TX — $200/Day Delivered to Site", "description": "Compact excavator available for Hubbard TX and surrounding Hill County areas.\n\n$200/day + $242.20 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Hubbard_eng": [
    {"title": "Track Loader Rental Hubbard TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent in Hubbard TX.\n\nGreat for grading, clearing, loading, and heavy site work in Hill County.\n\n$300/day. Delivery to Hubbard: $242.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Hubbard TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Hubbard TX. Stable on rough and soft terrain.\n\n$300/day. Hubbard delivery: $242.20.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Hubbard TX — $300/Day", "description": "Need a track loader in Hubbard TX? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $242.20 delivery to Hubbard.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Hubbard TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader for rent in Hubbard TX. Handles demanding terrain and heavy loads.\n\nDaily rate: $300. Delivery: $242.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Hubbard TX — Delivered to Your Site", "description": "Compact track loader rental serving Hubbard TX. Delivered and retrieved on your schedule.\n\n$300/day. Delivery: $242.20.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Curry Crossing_eng": [
    {"title": "Mini Excavator Rental Curry Crossing TX — $200/Day Delivered", "description": "Compact excavator for rent near Curry Crossing TX. Delivered to your property.\n\nIdeal for trenching, grading, utility lines, stump removal, and land clearing.\n\n$200/day. Delivery to Curry Crossing: $242.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator Rental Near Curry Crossing TX — Delivery Available", "description": "Kubota compact excavator available for Curry Crossing TX. We haul it to your site.\n\n$200/day + $242.60 delivery to Curry Crossing.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Curry Crossing TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in Curry Crossing TX. Handles rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $242.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex Near Curry Crossing TX — $200/Day", "description": "Kubota compact excavator rental serving Curry Crossing TX. Delivered and picked up from your site.\n\nRate: $200/day. Delivery: $242.60.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Curry Crossing TX — $200/Day Delivered", "description": "Compact excavator available for Curry Crossing TX and nearby areas.\n\n$200/day + $242.60 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Curry Crossing_eng": [
    {"title": "Track Loader Rental Curry Crossing TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Curry Crossing TX.\n\nPerfect for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Curry Crossing: $242.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Curry Crossing TX — Rent Daily", "description": "Kubota SVL75-2 track loader rental in Curry Crossing TX. Stable on rough and soft terrain.\n\n$300/day. Curry Crossing delivery: $242.60.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Curry Crossing TX — $300/Day", "description": "Need a track loader near Curry Crossing? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $242.60 delivery.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Curry Crossing TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Curry Crossing TX. Handles tough terrain and heavy loads.\n\nDaily rate: $300. Delivery: $242.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Curry Crossing TX — Delivered to Site", "description": "Compact track loader rental serving Curry Crossing TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $242.60.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Bowers_eng": [
    {"title": "Mini Excavator Rental Bowers TX — $200/Day Delivered", "description": "Compact excavator for rent near Bowers TX. Delivered to your job site.\n\nGreat for trenching, grading, drainage, stump removal, and land clearing.\n\n$200/day. Delivery to Bowers: $242.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Bowers TX — Delivery Available", "description": "Kubota compact excavator available for Bowers TX. We bring it to your site.\n\n$200/day + $242.60 delivery to Bowers.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Bowers TX Excavator Rental — Trenching & Land Clearing", "description": "Compact excavator rental in Bowers TX. Handles rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $242.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Bowers TX — $200/Day", "description": "Kubota compact excavator rental serving Bowers TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $242.60.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Bowers TX — $200/Day Delivered to Site", "description": "Compact excavator available for Bowers TX and surrounding areas.\n\n$200/day + $242.60 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Bowers_eng": [
    {"title": "Track Loader Rental Bowers TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Bowers TX.\n\nIdeal for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Bowers: $242.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Bowers TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Bowers TX. More traction than wheeled skid steers on rough terrain.\n\n$300/day. Bowers delivery: $242.60.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Bowers TX — $300/Day", "description": "Need a track loader near Bowers? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $242.60 delivery to Bowers.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Bowers TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Bowers TX. Handles tough ground conditions and heavy loads.\n\nDaily rate: $300. Delivery: $242.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Bowers TX — Delivered to Site", "description": "Compact track loader rental serving Bowers TX. Delivered and retrieved on your timeline.\n\n$300/day. Delivery: $242.60.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_New Colony_eng": [
    {"title": "Mini Excavator Rental New Colony TX — $200/Day Delivered", "description": "Compact excavator for rent near New Colony TX. Delivered to your property.\n\nPerfect for trenching, grading, utility work, stump removal, and land clearing.\n\n$200/day. Delivery to New Colony: $244.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator Rental Near New Colony TX — Delivery Available", "description": "Kubota compact excavator available for New Colony TX. We haul it to your site.\n\n$200/day + $244.60 delivery to New Colony.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "New Colony TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in New Colony TX. Ideal for rural lot work and light construction.\n\n$200/day. Delivery: $244.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in New Colony TX — $200/Day", "description": "Kubota compact excavator rental serving New Colony TX. Delivered and picked up from your site.\n\nRate: $200/day. Delivery: $244.60.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — New Colony TX — $200/Day Delivered to Site", "description": "Compact excavator available for New Colony TX and surrounding areas.\n\n$200/day + $244.60 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_New Colony_eng": [
    {"title": "Track Loader Rental New Colony TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near New Colony TX.\n\nGreat for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to New Colony: $244.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near New Colony TX — Rent Daily", "description": "Kubota SVL75-2 track loader rental in New Colony TX. Stable on rough and soft terrain.\n\n$300/day. New Colony delivery: $244.60.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — New Colony TX — $300/Day", "description": "Need a track loader near New Colony? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $244.60 delivery to New Colony.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "New Colony TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near New Colony TX. Handles tough terrain and heavy loads.\n\nDaily rate: $300. Delivery: $244.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — New Colony TX — Delivered to Site", "description": "Compact track loader rental serving New Colony TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $244.60.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Arnett_eng": [
    {"title": "Mini Excavator Rental Arnett TX — $200/Day Delivered", "description": "Compact excavator for rent near Arnett TX. Delivered to your job site.\n\nGreat for trenching, grading, drainage, stump removal, and land clearing.\n\n$200/day. Delivery to Arnett: $244.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Arnett TX — Delivery Available", "description": "Kubota compact excavator available for Arnett TX. We bring the machine to you.\n\n$200/day + $244.60 delivery to Arnett.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Arnett TX Excavator Rental — Trenching & Land Clearing", "description": "Compact excavator rental in Arnett TX. Handles rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $244.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Arnett TX — $200/Day", "description": "Kubota compact excavator rental serving Arnett TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $244.60.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Arnett TX — $200/Day Delivered to Site", "description": "Compact excavator available for Arnett TX and nearby areas.\n\n$200/day + $244.60 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Arnett_eng": [
    {"title": "Track Loader Rental Arnett TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Arnett TX.\n\nIdeal for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Arnett: $244.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Arnett TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Arnett TX. More traction than wheeled machines on rough terrain.\n\n$300/day. Arnett delivery: $244.60.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Arnett TX — $300/Day", "description": "Need a track loader near Arnett TX? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $244.60 delivery to Arnett.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Arnett TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Arnett TX. Handles tough ground conditions and heavy loads.\n\nDaily rate: $300. Delivery: $244.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Arnett TX — Delivered to Site", "description": "Compact track loader rental serving Arnett TX. Delivered and retrieved on your schedule.\n\n$300/day. Delivery: $244.60.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Malone_eng": [
    {"title": "Mini Excavator Rental Malone TX — $200/Day Delivered", "description": "Compact excavator for rent in Malone TX. Delivered to your job site in Hill County.\n\nIdeal for trenching, grading, drainage, stump removal, and land clearing.\n\n$200/day. Delivery to Malone: $244.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Malone TX — Delivery Available", "description": "Need a compact excavator in Malone? We haul it to your site.\n\n$200/day + $244.60 delivery to Malone.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Malone TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental serving Malone TX. Great for rural properties, utility lines, and site prep.\n\n$200/day. Delivery: $244.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Malone TX — $200/Day", "description": "Kubota compact excavator rental in Malone TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $244.60.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Malone TX — $200/Day Delivered to Site", "description": "Compact excavator available for Malone TX and surrounding Hill County areas.\n\n$200/day + $244.60 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Malone_eng": [
    {"title": "Track Loader Rental Malone TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent in Malone TX.\n\nGreat for grading, clearing, loading, and heavy site work in Hill County.\n\n$300/day. Delivery to Malone: $244.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Malone TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Malone TX. Stable on rough and soft terrain.\n\n$300/day. Malone delivery: $244.60.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Malone TX — $300/Day", "description": "Need a track loader in Malone TX? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $244.60 delivery to Malone.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Malone TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader for rent in Malone TX. Handles demanding terrain and heavy loads.\n\nDaily rate: $300. Delivery: $244.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Malone TX — Delivered to Your Site", "description": "Compact track loader rental serving Malone TX. Delivered and retrieved on your schedule.\n\n$300/day. Delivery: $244.60.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Zipperlandville_eng": [
    {"title": "Mini Excavator Rental Zipperlandville TX — $200/Day Delivered", "description": "Compact excavator for rent near Zipperlandville TX. Delivered to your property.\n\nPerfect for trenching, grading, utility work, stump removal, and land clearing.\n\n$200/day. Delivery to Zipperlandville: $245.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator Rental Near Zipperlandville TX — Delivery Available", "description": "Kubota compact excavator available for Zipperlandville TX. We haul it to your site.\n\n$200/day + $245.80 delivery to Zipperlandville.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Zipperlandville TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in Zipperlandville TX. Handles rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $245.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex Near Zipperlandville TX — $200/Day", "description": "Kubota compact excavator rental serving Zipperlandville TX. Delivered and picked up from your site.\n\nRate: $200/day. Delivery: $245.80.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Zipperlandville TX — $200/Day Delivered", "description": "Compact excavator available for Zipperlandville TX and nearby areas.\n\n$200/day + $245.80 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Zipperlandville_eng": [
    {"title": "Track Loader Rental Zipperlandville TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Zipperlandville TX.\n\nIdeal for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Zipperlandville: $245.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Zipperlandville TX — Rent Daily", "description": "Kubota SVL75-2 track loader rental in Zipperlandville TX. More traction than wheeled skid steers on rough terrain.\n\n$300/day. Delivery: $245.80.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Zipperlandville TX — $300/Day", "description": "Need a track loader near Zipperlandville? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $245.80 delivery.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Zipperlandville TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Zipperlandville TX. Handles tough terrain and heavy loads.\n\nDaily rate: $300. Delivery: $245.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Zipperlandville TX — Delivered to Site", "description": "Compact track loader rental serving Zipperlandville TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $245.80.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Big Hill_eng": [
    {"title": "Mini Excavator Rental Big Hill TX — $200/Day Delivered", "description": "Compact excavator for rent near Big Hill TX. Delivered to your job site.\n\nGreat for trenching, grading, utility lines, stump removal, and land clearing.\n\n$200/day. Delivery to Big Hill: $245.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Big Hill TX — Delivery Available", "description": "Kubota compact excavator available for Big Hill TX. We haul it to your site.\n\n$200/day + $245.80 delivery to Big Hill.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Big Hill TX Excavator Rental — Trenching & Land Clearing", "description": "Compact excavator rental in Big Hill TX. Handles rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $245.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Big Hill TX — $200/Day", "description": "Kubota compact excavator rental serving Big Hill TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $245.80.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Big Hill TX — $200/Day Delivered to Site", "description": "Compact excavator available for Big Hill TX and surrounding areas.\n\n$200/day + $245.80 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Big Hill_eng": [
    {"title": "Track Loader Rental Big Hill TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Big Hill TX.\n\nPerfect for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Big Hill: $245.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Big Hill TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Big Hill TX. More traction than wheeled skid steers on rough terrain.\n\n$300/day. Big Hill delivery: $245.80.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Big Hill TX — $300/Day", "description": "Need a track loader near Big Hill? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $245.80 delivery to Big Hill.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Big Hill TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Big Hill TX. Handles tough terrain and heavy loads.\n\nDaily rate: $300. Delivery: $245.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Big Hill TX — Delivered to Site", "description": "Compact track loader rental serving Big Hill TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $245.80.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Horn Hill_eng": [
    {"title": "Mini Excavator Rental Horn Hill TX — $200/Day Delivered", "description": "Compact excavator for rent near Horn Hill TX. Delivered to your job site.\n\nIdeal for trenching, grading, drainage, stump removal, and land clearing.\n\n$200/day. Delivery to Horn Hill: $247.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Horn Hill TX — Delivery Available", "description": "Kubota compact excavator available for Horn Hill TX. We bring the machine to you.\n\n$200/day + $247.00 delivery to Horn Hill.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Horn Hill TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in Horn Hill TX. Handles rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $247.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Horn Hill TX — $200/Day", "description": "Kubota compact excavator rental serving Horn Hill TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $247.00.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Horn Hill TX — $200/Day Delivered to Site", "description": "Compact excavator available for Horn Hill TX and nearby areas.\n\n$200/day + $247.00 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Horn Hill_eng": [
    {"title": "Track Loader Rental Horn Hill TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Horn Hill TX.\n\nGreat for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Horn Hill: $247.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Horn Hill TX — Rent Daily", "description": "Kubota SVL75-2 track loader rental in Horn Hill TX. Stable on rough and soft terrain.\n\n$300/day. Horn Hill delivery: $247.00.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Horn Hill TX — $300/Day", "description": "Need a track loader near Horn Hill? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $247.00 delivery to Horn Hill.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Horn Hill TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Horn Hill TX. Handles tough terrain and heavy loads.\n\nDaily rate: $300. Delivery: $247.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Horn Hill TX — Delivered to Site", "description": "Compact track loader rental serving Horn Hill TX. Delivered and retrieved on your timeline.\n\n$300/day. Delivery: $247.00.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Rosebud_eng": [
    {"title": "Mini Excavator Rental Rosebud TX — $200/Day Delivered", "description": "Compact excavator for rent in Rosebud TX. Delivered to your job site in Falls County.\n\nPerfect for trenching, grading, utility work, drainage, and land clearing.\n\n$200/day. Delivery to Rosebud: $248.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent in Rosebud TX — Delivery Available", "description": "Need a compact excavator in Rosebud? We haul it to your site.\n\n$200/day + $248.60 delivery to Rosebud.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rosebud TX Excavator Rental — Trenching, Grading & Clearing", "description": "Compact excavator rental serving Rosebud TX. Ideal for rural properties, fence lines, and construction prep.\n\n$200/day. Delivery: $248.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Rosebud TX — $200/Day", "description": "Kubota compact excavator rental in Rosebud TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $248.60.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Rosebud TX — $200/Day Delivered to Site", "description": "Compact excavator available for Rosebud TX and surrounding Falls County areas.\n\n$200/day + $248.60 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Rosebud_eng": [
    {"title": "Track Loader Rental Rosebud TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent in Rosebud TX.\n\nGreat for grading, clearing, loading, and heavy site work in Falls County.\n\n$300/day. Delivery to Rosebud: $248.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader in Rosebud TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental serving Rosebud TX. Stable and powerful on rough terrain.\n\n$300/day. Rosebud delivery: $248.60.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Rosebud TX — $300/Day", "description": "Renting the Kubota SVL75-2 track loader to Rosebud TX. We deliver and pick up.\n\n$300/day + $248.60 delivery to Rosebud.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rosebud TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader for rent in Rosebud TX. Handles demanding terrain and heavy loads.\n\nDaily rate: $300. Delivery: $248.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Rosebud TX — Delivered to Your Site", "description": "Compact track loader rental serving Rosebud TX. Delivered and retrieved on your schedule.\n\n$300/day. Delivery: $248.60.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Stranger_eng": [
    {"title": "Mini Excavator Rental Stranger TX — $200/Day Delivered", "description": "Compact excavator for rent near Stranger TX. Delivered to your job site.\n\nGreat for trenching, grading, drainage, stump removal, and land clearing.\n\n$200/day. Delivery to Stranger: $249.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Stranger TX — Delivery Available", "description": "Kubota compact excavator available for Stranger TX. We bring the machine to you.\n\n$200/day + $249.40 delivery to Stranger.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Stranger TX Excavator Rental — Trenching & Land Clearing", "description": "Compact excavator rental in Stranger TX. Handles rural lots, fence lines, and light construction.\n\n$200/day. Delivery: $249.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Stranger TX — $200/Day", "description": "Kubota compact excavator rental serving Stranger TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $249.40.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Stranger TX — $200/Day Delivered to Site", "description": "Compact excavator available for Stranger TX and surrounding areas.\n\n$200/day + $249.40 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Stranger_eng": [
    {"title": "Track Loader Rental Stranger TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Stranger TX.\n\nIdeal for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Stranger: $249.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Stranger TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Stranger TX. More traction than wheeled skid steers on rough terrain.\n\n$300/day. Stranger delivery: $249.40.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Stranger TX — $300/Day", "description": "Need a track loader near Stranger? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $249.40 delivery to Stranger.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Stranger TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Stranger TX. Handles tough ground conditions and heavy loads.\n\nDaily rate: $300. Delivery: $249.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Stranger TX — Delivered to Site", "description": "Compact track loader rental serving Stranger TX. Delivered and retrieved on your schedule.\n\n$300/day. Delivery: $249.40.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Crossroad Store_eng": [
    {"title": "Mini Excavator Rental Crossroad Store TX — $200/Day Delivered", "description": "Compact excavator for rent near Crossroad Store TX. Delivered to your property.\n\nPerfect for trenching, grading, utility work, stump removal, and land clearing.\n\n$200/day. Delivery to Crossroad Store: $250.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator Rental Near Crossroad Store TX — Delivery Available", "description": "Kubota compact excavator available for Crossroad Store TX. We haul it to your site.\n\n$200/day + $250.20 delivery.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Crossroad Store TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in Crossroad Store TX. Ideal for rural lot work and light construction.\n\n$200/day. Delivery: $250.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex Near Crossroad Store TX — $200/Day", "description": "Kubota compact excavator rental serving Crossroad Store TX. Delivered and picked up from your site.\n\nRate: $200/day. Delivery: $250.20.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Crossroad Store TX — $200/Day Delivered", "description": "Compact excavator available for Crossroad Store TX and surrounding areas.\n\n$200/day + $250.20 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Crossroad Store_eng": [
    {"title": "Track Loader Rental Crossroad Store TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Crossroad Store TX.\n\nGreat for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Crossroad Store: $250.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Crossroad Store TX — Rent Daily", "description": "Kubota SVL75-2 track loader rental in Crossroad Store TX. Stable on rough and soft terrain.\n\n$300/day. Delivery: $250.20.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Crossroad Store TX — $300/Day", "description": "Need a track loader near Crossroad Store? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $250.20 delivery.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Crossroad Store TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Crossroad Store TX. Handles tough terrain and heavy loads.\n\nDaily rate: $300. Delivery: $250.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Crossroad Store TX — Delivered to Site", "description": "Compact track loader rental serving Crossroad Store TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $250.20.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Smiths Bend_eng": [
    {"title": "Mini Excavator Rental Smiths Bend TX — $200/Day Delivered", "description": "Compact excavator for rent near Smiths Bend TX. Delivered to your job site.\n\nIdeal for trenching, grading, utility lines, stump removal, and land clearing.\n\n$200/day. Delivery to Smiths Bend: $250.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Smiths Bend TX — Delivery Available", "description": "Kubota compact excavator available for Smiths Bend TX. We bring the machine to you.\n\n$200/day + $250.60 delivery to Smiths Bend.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Smiths Bend TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in Smiths Bend TX. Handles rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $250.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Smiths Bend TX — $200/Day", "description": "Kubota compact excavator rental serving Smiths Bend TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $250.60.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Smiths Bend TX — $200/Day Delivered to Site", "description": "Compact excavator available for Smiths Bend TX and nearby areas.\n\n$200/day + $250.60 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Smiths Bend_eng": [
    {"title": "Track Loader Rental Smiths Bend TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Smiths Bend TX.\n\nPerfect for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Smiths Bend: $250.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Smiths Bend TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Smiths Bend TX. More traction than wheeled skid steers on rough terrain.\n\n$300/day. Smiths Bend delivery: $250.60.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Smiths Bend TX — $300/Day", "description": "Need a track loader near Smiths Bend? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $250.60 delivery to Smiths Bend.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Smiths Bend TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Smiths Bend TX. Handles tough ground conditions and heavy loads.\n\nDaily rate: $300. Delivery: $250.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Smiths Bend TX — Delivered to Site", "description": "Compact track loader rental serving Smiths Bend TX. Delivered and retrieved on your timeline.\n\n$300/day. Delivery: $250.60.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Yarrelton_eng": [
    {"title": "Mini Excavator Rental Yarrelton TX — $200/Day Delivered", "description": "Compact excavator for rent near Yarrelton TX. Delivered to your property.\n\nGreat for trenching, grading, drainage, stump removal, and land clearing.\n\n$200/day. Delivery to Yarrelton: $250.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Yarrelton TX — Delivery Available", "description": "Kubota compact excavator available for Yarrelton TX. We haul it to your site.\n\n$200/day + $250.60 delivery to Yarrelton.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Yarrelton TX Excavator Rental — Trenching & Land Clearing", "description": "Compact excavator rental in Yarrelton TX. Handles rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $250.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Yarrelton TX — $200/Day", "description": "Kubota compact excavator rental serving Yarrelton TX. Delivered and picked up from your site.\n\nRate: $200/day. Delivery: $250.60.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Yarrelton TX — $200/Day Delivered to Site", "description": "Compact excavator available for Yarrelton TX and surrounding areas.\n\n$200/day + $250.60 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Yarrelton_eng": [
    {"title": "Track Loader Rental Yarrelton TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Yarrelton TX.\n\nIdeal for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Yarrelton: $250.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Yarrelton TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Yarrelton TX. More traction than wheeled machines on rough terrain.\n\n$300/day. Yarrelton delivery: $250.60.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Yarrelton TX — $300/Day", "description": "Need a track loader near Yarrelton? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $250.60 delivery to Yarrelton.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Yarrelton TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Yarrelton TX. Handles tough terrain and heavy loads.\n\nDaily rate: $300. Delivery: $250.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Yarrelton TX — Delivered to Site", "description": "Compact track loader rental serving Yarrelton TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $250.60.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Prairie Valley_eng": [
    {"title": "Mini Excavator Rental Prairie Valley TX — $200/Day Delivered", "description": "Compact excavator for rent near Prairie Valley TX. Delivered to your job site.\n\nPerfect for trenching, grading, utility lines, stump removal, and land clearing.\n\n$200/day. Delivery to Prairie Valley: $251.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator Rental Near Prairie Valley TX — Delivery Available", "description": "Kubota compact excavator available for Prairie Valley TX. We bring the machine to you.\n\n$200/day + $251.00 delivery to Prairie Valley.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Prairie Valley TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in Prairie Valley TX. Handles rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $251.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Prairie Valley TX — $200/Day", "description": "Kubota compact excavator rental serving Prairie Valley TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $251.00.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Prairie Valley TX — $200/Day Delivered to Site", "description": "Compact excavator available for Prairie Valley TX and surrounding areas.\n\n$200/day + $251.00 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Prairie Valley_eng": [
    {"title": "Track Loader Rental Prairie Valley TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Prairie Valley TX.\n\nGreat for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Prairie Valley: $251.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Prairie Valley TX — Rent Daily", "description": "Kubota SVL75-2 track loader rental in Prairie Valley TX. Stable on rough and soft terrain.\n\n$300/day. Prairie Valley delivery: $251.00.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Prairie Valley TX — $300/Day", "description": "Need a track loader near Prairie Valley? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $251.00 delivery to Prairie Valley.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Prairie Valley TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Prairie Valley TX. Handles demanding terrain and heavy loads.\n\nDaily rate: $300. Delivery: $251.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Prairie Valley TX — Delivered to Site", "description": "Compact track loader rental serving Prairie Valley TX. Delivered and retrieved on your schedule.\n\n$300/day. Delivery: $251.00.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Edgeworth_eng": [
    {"title": "Mini Excavator Rental Edgeworth TX — $200/Day Delivered", "description": "Compact excavator for rent near Edgeworth TX. Delivered to your job site.\n\nGreat for trenching, grading, drainage, stump removal, and land clearing.\n\n$200/day. Delivery to Edgeworth: $251.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Edgeworth TX — Delivery Available", "description": "Kubota compact excavator available for Edgeworth TX. We haul it to your site.\n\n$200/day + $251.40 delivery to Edgeworth.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Edgeworth TX Excavator Rental — Trenching & Land Clearing", "description": "Compact excavator rental in Edgeworth TX. Handles rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $251.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Edgeworth TX — $200/Day", "description": "Kubota compact excavator rental serving Edgeworth TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $251.40.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Edgeworth TX — $200/Day Delivered to Site", "description": "Compact excavator available for Edgeworth TX and surrounding areas.\n\n$200/day + $251.40 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Edgeworth_eng": [
    {"title": "Track Loader Rental Edgeworth TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Edgeworth TX.\n\nIdeal for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Edgeworth: $251.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Edgeworth TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Edgeworth TX. More traction than wheeled skid steers on rough terrain.\n\n$300/day. Edgeworth delivery: $251.40.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Edgeworth TX — $300/Day", "description": "Need a track loader near Edgeworth? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $251.40 delivery to Edgeworth.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Edgeworth TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Edgeworth TX. Handles tough terrain and heavy loads.\n\nDaily rate: $300. Delivery: $251.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Edgeworth TX — Delivered to Site", "description": "Compact track loader rental serving Edgeworth TX. Delivered and retrieved on your timeline.\n\n$300/day. Delivery: $251.40.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Odds_eng": [
    {"title": "Mini Excavator Rental Odds TX — $200/Day Delivered", "description": "Compact excavator for rent near Odds TX. Delivered to your job site.\n\nGreat for trenching, grading, utility lines, stump removal, and land clearing.\n\n$200/day. Delivery to Odds: $251.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Odds TX — Delivery Available", "description": "Kubota compact excavator available for Odds TX. We bring the machine to you.\n\n$200/day + $251.80 delivery to Odds.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Odds TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in Odds TX. Handles rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $251.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Odds TX — $200/Day", "description": "Kubota compact excavator rental serving Odds TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $251.80.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Odds TX — $200/Day Delivered to Site", "description": "Compact excavator available for Odds TX and surrounding areas.\n\n$200/day + $251.80 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Odds_eng": [
    {"title": "Track Loader Rental Odds TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Odds TX.\n\nPerfect for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Odds: $251.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Odds TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Odds TX. Stable on rough and soft terrain.\n\n$300/day. Odds delivery: $251.80.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Odds TX — $300/Day", "description": "Need a track loader near Odds TX? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $251.80 delivery to Odds.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Odds TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Odds TX. Handles tough ground conditions and heavy loads.\n\nDaily rate: $300. Delivery: $251.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Odds TX — Delivered to Site", "description": "Compact track loader rental serving Odds TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $251.80.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Beacon_eng": [
    {"title": "Mini Excavator Rental Beacon TX — $200/Day Delivered", "description": "Compact excavator for rent near Beacon TX. Delivered to your property.\n\nIdeal for trenching, grading, drainage, stump removal, and land clearing.\n\n$200/day. Delivery to Beacon: $252.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Beacon TX — Delivery Available", "description": "Kubota compact excavator available for Beacon TX. We haul it to your site.\n\n$200/day + $252.20 delivery to Beacon.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Beacon TX Excavator Rental — Trenching & Land Clearing", "description": "Compact excavator rental in Beacon TX. Handles rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $252.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Beacon TX — $200/Day", "description": "Kubota compact excavator rental serving Beacon TX. Delivered and picked up from your site.\n\nRate: $200/day. Delivery: $252.20.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Beacon TX — $200/Day Delivered to Site", "description": "Compact excavator available for Beacon TX and surrounding areas.\n\n$200/day + $252.20 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Beacon_eng": [
    {"title": "Track Loader Rental Beacon TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Beacon TX.\n\nGreat for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Beacon: $252.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Beacon TX — Rent Daily", "description": "Kubota SVL75-2 track loader rental in Beacon TX. More traction than wheeled machines on rough terrain.\n\n$300/day. Beacon delivery: $252.20.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Beacon TX — $300/Day", "description": "Need a track loader near Beacon? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $252.20 delivery to Beacon.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Beacon TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Beacon TX. Handles tough terrain and heavy loads.\n\nDaily rate: $300. Delivery: $252.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Beacon TX — Delivered to Site", "description": "Compact track loader rental serving Beacon TX. Delivered and retrieved on your schedule.\n\n$300/day. Delivery: $252.20.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Spivey Crossing_eng": [
    {"title": "Mini Excavator Rental Spivey Crossing TX — $200/Day Delivered", "description": "Compact excavator for rent near Spivey Crossing TX. Delivered to your job site.\n\nPerfect for trenching, grading, utility lines, stump removal, and land clearing.\n\n$200/day. Delivery to Spivey Crossing: $253.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator Rental Near Spivey Crossing TX — Delivery Available", "description": "Kubota compact excavator available for Spivey Crossing TX. We bring the machine to you.\n\n$200/day + $253.00 delivery to Spivey Crossing.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Spivey Crossing TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in Spivey Crossing TX. Handles rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $253.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex Near Spivey Crossing TX — $200/Day", "description": "Kubota compact excavator rental serving Spivey Crossing TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $253.00.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Spivey Crossing TX — $200/Day Delivered", "description": "Compact excavator available for Spivey Crossing TX and surrounding areas.\n\n$200/day + $253.00 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Spivey Crossing_eng": [
    {"title": "Track Loader Rental Spivey Crossing TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Spivey Crossing TX.\n\nIdeal for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Spivey Crossing: $253.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Spivey Crossing TX — Rent Daily", "description": "Kubota SVL75-2 track loader rental in Spivey Crossing TX. Stable on rough and soft terrain.\n\n$300/day. Spivey Crossing delivery: $253.00.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Spivey Crossing TX — $300/Day", "description": "Need a track loader near Spivey Crossing? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $253.00 delivery to Spivey Crossing.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Spivey Crossing TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Spivey Crossing TX. Handles tough terrain and heavy loads.\n\nDaily rate: $300. Delivery: $253.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Spivey Crossing TX — Delivered to Site", "description": "Compact track loader rental serving Spivey Crossing TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $253.00.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ]
}
with open("data/batch_temp.json", "w") as f:
    json.dump(batch15, f, indent=2)
print(f"Written {len(batch15)} slots to batch_temp.json")
