import json
batch14 = {
  "mini-ex_Meeks_eng": [
    {"title": "Mini Excavator Rental Meeks TX — $200/Day Delivered", "description": "Compact excavator for rent near Meeks TX. Delivered to your job site.\n\nGreat for trenching, grading, utility lines, stump removal, and land clearing.\n\n$200/day. Delivery to Meeks: $237.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Meeks TX — Delivery Available", "description": "Kubota compact excavator available for Meeks TX. We haul it to your site.\n\n$200/day + $237.40 delivery to Meeks.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Meeks TX Excavator Rental — Trenching, Grading & More", "description": "Compact excavator rental in Meeks TX. Ideal for rural lot work, fence lines, and light construction.\n\n$200/day. Delivery: $237.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Meeks TX — $200/Day", "description": "Kubota compact excavator rental serving Meeks TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $237.40.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Meeks TX — $200/Day Delivered to Site", "description": "Compact excavator available for Meeks TX and surrounding areas.\n\n$200/day + $237.40 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Meeks_eng": [
    {"title": "Track Loader Rental Meeks TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Meeks TX.\n\nIdeal for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Meeks: $237.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Meeks TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Meeks TX. More traction than wheeled skid steers on rough terrain.\n\n$300/day. Meeks delivery: $237.40.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Meeks TX — $300/Day", "description": "Need a track loader near Meeks TX? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $237.40 delivery to Meeks.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Meeks TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Meeks TX. Handles tough terrain and heavy loads.\n\nDaily rate: $300. Delivery: $237.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Meeks TX — Delivered to Site", "description": "Compact track loader rental serving Meeks TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $237.40.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Salado_eng": [
    {"title": "Mini Excavator Rental Salado TX — $200/Day Delivered", "description": "Compact excavator for rent in Salado TX. Delivered to your job site in Bell County.\n\nPerfect for trenching, drainage, grading, stump removal, and land clearing.\n\n$200/day. Delivery to Salado: $238.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent in Salado TX — Delivery Available", "description": "Need a compact excavator in Salado? We bring the machine to you.\n\nKubota compact excavator — rubber tracks, blade, handles tight and soft lots.\n\n$200/day + $238.20 delivery to Salado.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Salado TX Excavator Rental — Trenching, Grading & Clearing", "description": "Compact excavator rental serving Salado TX. Great for residential lots, utility lines, pool excavation, and site prep.\n\n$200/day. Delivery: $238.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Salado TX — $200/Day", "description": "Kubota compact excavator rental in Salado TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $238.20.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Salado TX — $200/Day Delivered to Site", "description": "Compact excavator available for Salado TX and the surrounding Bell County area.\n\n$200/day + $238.20 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Salado_eng": [
    {"title": "Track Loader Rental Salado TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent in Salado TX.\n\nPerfect for grading, clearing, loading, and heavy site work across Bell County.\n\n$300/day. Delivery to Salado: $238.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader in Salado TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental serving Salado TX. Stable and powerful on rough or soft terrain.\n\n$300/day. Salado delivery: $238.20.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Salado TX — $300/Day", "description": "Renting the Kubota SVL75-2 track loader to Salado TX. We deliver and pick up.\n\n$300/day + $238.20 delivery to Salado.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Salado TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader for rent in Salado TX. Handles demanding terrain and heavy loads.\n\nDaily rate: $300. Delivery: $238.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Salado TX — Delivered to Your Site", "description": "Compact track loader rental serving Salado TX. Delivered and retrieved on your schedule.\n\n$300/day. Delivery: $238.20.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Womack_eng": [
    {"title": "Mini Excavator Rental Womack TX — $200/Day Delivered", "description": "Compact excavator for rent near Womack TX. Delivered to your property.\n\nIdeal for trenching, grading, drainage, stump removal, and land clearing.\n\n$200/day. Delivery to Womack: $239.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator Rental Near Womack TX — Delivery Available", "description": "Kubota compact excavator available for Womack TX. We haul it to your site.\n\n$200/day + $239.80 delivery to Womack.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Womack TX Excavator Rental — Trenching & Land Clearing", "description": "Compact excavator rental in Womack TX. Handles rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $239.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Womack TX — $200/Day", "description": "Kubota compact excavator rental serving Womack TX. Delivered and picked up from your site.\n\nRate: $200/day. Delivery: $239.80.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Womack TX — $200/Day Delivered to Site", "description": "Compact excavator available for Womack TX and nearby areas.\n\n$200/day + $239.80 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Womack_eng": [
    {"title": "Track Loader Rental Womack TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Womack TX.\n\nGreat for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Womack: $239.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Womack TX — Rent Daily", "description": "Kubota SVL75-2 track loader rental in Womack TX. Stable on rough and soft terrain.\n\n$300/day. Womack delivery: $239.80.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Womack TX — $300/Day", "description": "Need a track loader near Womack? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $239.80 delivery to Womack.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Womack TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Womack TX. Handles tough terrain and heavy loads.\n\nDaily rate: $300. Delivery: $239.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Womack TX — Delivered to Site", "description": "Compact track loader rental serving Womack TX. Delivered and picked up on your timeline.\n\n$300/day. Delivery: $239.80.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Chatt_eng": [
    {"title": "Mini Excavator Rental Chatt TX — $200/Day Delivered", "description": "Compact excavator for rent near Chatt TX. Delivered to your job site.\n\nPerfect for trenching, grading, utility lines, stump removal, and land clearing.\n\n$200/day. Delivery to Chatt: $239.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Chatt TX — Delivery Available", "description": "Kubota compact excavator available for Chatt TX. We bring the machine to you.\n\n$200/day + $239.80 delivery to Chatt.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Chatt TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in Chatt TX. Ideal for rural lot work and light construction projects.\n\n$200/day. Delivery: $239.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Chatt TX — $200/Day", "description": "Kubota compact excavator rental serving Chatt TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $239.80.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Chatt TX — $200/Day Delivered to Site", "description": "Compact excavator available for Chatt TX and surrounding areas.\n\n$200/day + $239.80 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Chatt_eng": [
    {"title": "Track Loader Rental Chatt TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Chatt TX.\n\nIdeal for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Chatt: $239.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Chatt TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Chatt TX. More traction than wheeled machines on rough terrain.\n\n$300/day. Chatt delivery: $239.80.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Chatt TX — $300/Day", "description": "Need a track loader near Chatt TX? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $239.80 delivery to Chatt.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Chatt TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Chatt TX. Handles tough ground conditions and heavy loads.\n\nDaily rate: $300. Delivery: $239.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Chatt TX — Delivered to Site", "description": "Compact track loader rental serving Chatt TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $239.80.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Wilderville_eng": [
    {"title": "Mini Excavator Rental Wilderville TX — $200/Day Delivered", "description": "Compact excavator for rent near Wilderville TX. Delivered to your property.\n\nGreat for trenching, grading, utility work, stump removal, and land clearing.\n\n$200/day. Delivery to Wilderville: $240.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator Rental Near Wilderville TX — Delivery Available", "description": "Kubota compact excavator available for Wilderville TX. We haul it to your site.\n\n$200/day + $240.20 delivery to Wilderville.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Wilderville TX Excavator Rental — Trenching & Land Clearing", "description": "Compact excavator rental in Wilderville TX. Handles rural lots, fence lines, and light construction work.\n\n$200/day. Delivery: $240.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Wilderville TX — $200/Day", "description": "Kubota compact excavator rental serving Wilderville TX. Delivered and picked up from your site.\n\nRate: $200/day. Delivery: $240.20.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Wilderville TX — $200/Day Delivered to Site", "description": "Compact excavator available for Wilderville TX and surrounding areas.\n\n$200/day + $240.20 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Wilderville_eng": [
    {"title": "Track Loader Rental Wilderville TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Wilderville TX.\n\nPerfect for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Wilderville: $240.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Wilderville TX — Rent Daily", "description": "Kubota SVL75-2 track loader rental in Wilderville TX. Stable on rough and soft terrain.\n\n$300/day. Wilderville delivery: $240.20.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Wilderville TX — $300/Day", "description": "Need a track loader near Wilderville? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $240.20 delivery to Wilderville.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Wilderville TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Wilderville TX. Handles demanding terrain and heavy loads.\n\nDaily rate: $300. Delivery: $240.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Wilderville TX — Delivered to Site", "description": "Compact track loader rental serving Wilderville TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $240.20.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Reagan_eng": [
    {"title": "Mini Excavator Rental Reagan TX — $200/Day Delivered", "description": "Compact excavator for rent near Reagan TX. Delivered to your job site.\n\nIdeal for trenching, grading, drainage, stump removal, and land clearing.\n\n$200/day. Delivery to Reagan: $240.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Reagan TX — Delivery Available", "description": "Kubota compact excavator available for Reagan TX. We bring the machine to you.\n\n$200/day + $240.20 delivery to Reagan.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Reagan TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in Reagan TX. Handles rural lots, fence lines, and utility work with ease.\n\n$200/day. Delivery: $240.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Reagan TX — $200/Day", "description": "Kubota compact excavator rental serving Reagan TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $240.20.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Reagan TX — $200/Day Delivered to Site", "description": "Compact excavator available for Reagan TX and surrounding Falls County areas.\n\n$200/day + $240.20 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Reagan_eng": [
    {"title": "Track Loader Rental Reagan TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Reagan TX.\n\nGreat for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Reagan: $240.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Reagan TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Reagan TX. More traction than wheeled skid steers on rough terrain.\n\n$300/day. Reagan delivery: $240.20.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Reagan TX — $300/Day", "description": "Need a track loader near Reagan TX? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $240.20 delivery to Reagan.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Reagan TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Reagan TX. Handles tough ground conditions and heavy loads.\n\nDaily rate: $300. Delivery: $240.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Reagan TX — Delivered to Site", "description": "Compact track loader rental serving Reagan TX. Delivered and retrieved on your timeline.\n\n$300/day. Delivery: $240.20.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Nolanville_eng": [
    {"title": "Mini Excavator Rental Nolanville TX — $200/Day Delivered", "description": "Compact excavator for rent in Nolanville TX. Delivered to your job site in Bell County.\n\nGreat for trenching, drainage, grading, stump removal, and land clearing.\n\n$200/day. Delivery to Nolanville: $240.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent in Nolanville TX — Delivery Available", "description": "Need a compact excavator in Nolanville? We haul it to your site.\n\n$200/day + $240.60 delivery to Nolanville.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Nolanville TX Excavator Rental — Trenching, Grading & Clearing", "description": "Compact excavator rental serving Nolanville TX. Ideal for residential and commercial dig work near Killeen.\n\n$200/day. Delivery: $240.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Nolanville TX — $200/Day", "description": "Kubota compact excavator rental in Nolanville TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $240.60.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Nolanville TX — $200/Day Delivered to Site", "description": "Compact excavator available for Nolanville TX and the surrounding Bell County area.\n\n$200/day + $240.60 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Nolanville_eng": [
    {"title": "Track Loader Rental Nolanville TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent in Nolanville TX.\n\nPerfect for grading, clearing, loading, and heavy site work near Killeen.\n\n$300/day. Delivery to Nolanville: $240.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader in Nolanville TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental serving Nolanville TX. Stable and powerful on rough terrain.\n\n$300/day. Nolanville delivery: $240.60.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Nolanville TX — $300/Day", "description": "Renting the Kubota SVL75-2 track loader to Nolanville TX. We deliver and pick up.\n\n$300/day + $240.60 delivery to Nolanville.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Nolanville TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader for rent in Nolanville TX. Handles demanding terrain and heavy loads.\n\nDaily rate: $300. Delivery: $240.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Nolanville TX — Delivered to Your Site", "description": "Compact track loader rental serving Nolanville TX. Delivered and retrieved on your schedule.\n\n$300/day. Delivery: $240.60.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Delia_eng": [
    {"title": "Mini Excavator Rental Delia TX — $200/Day Delivered", "description": "Compact excavator for rent near Delia TX. Delivered to your property.\n\nPerfect for trenching, grading, utility lines, stump removal, and land clearing.\n\n$200/day. Delivery to Delia: $241.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Delia TX — Delivery Available", "description": "Kubota compact excavator available for Delia TX. We haul it to your site.\n\n$200/day + $241.00 delivery to Delia.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Delia TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in Delia TX. Handles rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $241.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Delia TX — $200/Day", "description": "Kubota compact excavator rental serving Delia TX. Delivered and picked up from your site.\n\nRate: $200/day. Delivery: $241.00.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Delia TX — $200/Day Delivered to Site", "description": "Compact excavator available for Delia TX and surrounding areas.\n\n$200/day + $241.00 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Delia_eng": [
    {"title": "Track Loader Rental Delia TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Delia TX.\n\nIdeal for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Delia: $241.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Delia TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Delia TX. More traction than wheeled skid steers on rough terrain.\n\n$300/day. Delia delivery: $241.00.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Delia TX — $300/Day", "description": "Need a track loader near Delia? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $241.00 delivery to Delia.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Delia TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Delia TX. Handles tough ground conditions and heavy loads.\n\nDaily rate: $300. Delivery: $241.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Delia TX — Delivered to Site", "description": "Compact track loader rental serving Delia TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $241.00.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Menlow_eng": [
    {"title": "Mini Excavator Rental Menlow TX — $200/Day Delivered", "description": "Compact excavator for rent near Menlow TX. Delivered to your job site.\n\nGreat for trenching, grading, drainage, stump removal, and land clearing.\n\n$200/day. Delivery to Menlow: $241.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Menlow TX — Delivery Available", "description": "Kubota compact excavator available for Menlow TX. We bring the machine to you.\n\n$200/day + $241.80 delivery to Menlow.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Menlow TX Excavator Rental — Trenching & Land Clearing", "description": "Compact excavator rental in Menlow TX. Ideal for rural lot work and light construction.\n\n$200/day. Delivery: $241.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Menlow TX — $200/Day", "description": "Kubota compact excavator rental serving Menlow TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $241.80.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Menlow TX — $200/Day Delivered to Site", "description": "Compact excavator available for Menlow TX and nearby areas.\n\n$200/day + $241.80 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Menlow_eng": [
    {"title": "Track Loader Rental Menlow TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Menlow TX.\n\nGreat for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Menlow: $241.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Menlow TX — Rent Daily", "description": "Kubota SVL75-2 track loader rental in Menlow TX. Stable on rough and soft terrain.\n\n$300/day. Menlow delivery: $241.80.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Menlow TX — $300/Day", "description": "Need a track loader near Menlow? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $241.80 delivery to Menlow.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Menlow TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Menlow TX. Handles demanding terrain and heavy loads.\n\nDaily rate: $300. Delivery: $241.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Menlow TX — Delivered to Site", "description": "Compact track loader rental serving Menlow TX. Delivered and retrieved on your timeline.\n\n$300/day. Delivery: $241.80.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Holland_eng": [
    {"title": "Mini Excavator Rental Holland TX — $200/Day Delivered", "description": "Compact excavator for rent in Holland TX. Delivered to your job site in Bell County.\n\nPerfect for trenching, grading, utility work, drainage, and land clearing.\n\n$200/day. Delivery to Holland: $241.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Holland TX — Delivery Available", "description": "Need a compact excavator in Holland TX? We haul it to your site.\n\n$200/day + $241.80 delivery to Holland.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Holland TX Excavator Rental — Trenching, Grading & Clearing", "description": "Compact excavator rental serving Holland TX. Ideal for rural lots, fence lines, and construction prep.\n\n$200/day. Delivery: $241.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Holland TX — $200/Day", "description": "Kubota compact excavator rental in Holland TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $241.80.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Holland TX — $200/Day Delivered to Site", "description": "Compact excavator available for Holland TX and the surrounding Bell County area.\n\n$200/day + $241.80 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Holland_eng": [
    {"title": "Track Loader Rental Holland TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent in Holland TX.\n\nIdeal for grading, clearing, loading, and heavy site work in Bell County.\n\n$300/day. Delivery to Holland: $241.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Holland TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Holland TX. More traction than wheeled skid steers on rough terrain.\n\n$300/day. Holland delivery: $241.80.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Holland TX — $300/Day", "description": "Need a track loader in Holland TX? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $241.80 delivery to Holland.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Holland TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader for rent in Holland TX. Handles tough ground conditions and heavy loads.\n\nDaily rate: $300. Delivery: $241.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Holland TX — Delivered to Your Site", "description": "Compact track loader rental serving Holland TX. Delivered and retrieved on your schedule.\n\n$300/day. Delivery: $241.80.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ]
}
with open("data/batch_temp.json", "w") as f:
    json.dump(batch14, f, indent=2)
print(f"Written {len(batch14)} slots to batch_temp.json")
