import json
batch10 = {
  "mini-ex_Rogers Hill_eng": [
    {"title": "Mini Excavator Rental Rogers Hill TX — $200/day", "description": "Compact excavator available for Rogers Hill and nearby areas. Great for trenching, grading, pool excavation, fence post holes, and land clearing.\n\n$200/day. Delivery to Rogers Hill: $202.60.\n\nKubota compact excavator, rubber tracks, blade included.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Rogers Hill — Delivery Available", "description": "Need a compact excavator in Rogers Hill? We deliver to your job site.\n\nPerfect for utility work, drainage, tree stump removal, and site prep.\n\n$200/day. Rogers Hill delivery: $202.60.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Rogers Hill TX — $200/Day Delivered", "description": "Kubota compact excavator rental serving Rogers Hill TX.\n\nIdeal for digging trenches, clearing brush, grading driveways, and excavating foundations.\n\nDaily rate: $200. Delivery to Rogers Hill: $202.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rogers Hill Excavator Rental — Trenching, Grading, Clearing", "description": "Compact excavator for rent in Rogers Hill TX. We haul it to you.\n\nUses: trenching, drainage, demolition, stump removal, land clearing.\n\n$200/day + $202.60 delivery to Rogers Hill.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Rogers Hill TX Delivery — $200/Day", "description": "Renting a compact excavator near Rogers Hill TX. Delivered to your site, picked up when done.\n\nGreat for residential and light commercial dig work.\n\nRate: $200/day. Delivery: $202.60.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Rogers Hill_eng": [
    {"title": "Track Loader Rental Rogers Hill TX — $300/Day Delivered", "description": "Kubota SVL75-2 track loader available for Rogers Hill area. Heavy-duty skid steer on tracks — ideal for grading, pushing, loading, and site work.\n\n$300/day. Delivery to Rogers Hill: $202.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Rogers Hill — Rent by the Day", "description": "Kubota SVL75-2 compact track loader serving Rogers Hill TX. More stable than wheeled skid steers on rough terrain.\n\n$300/day. Rogers Hill delivery: $202.60.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Rogers Hill TX — $300/Day", "description": "Need a track loader in Rogers Hill? We deliver the Kubota SVL75-2 to your job site.\n\nGreat for grading driveways, clearing land, moving material, and construction prep.\n\n$300/day + $202.60 delivery.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rogers Hill Track Loader Rental — Kubota SVL75-2", "description": "Kubota SVL75-2 track loader rental in Rogers Hill TX. Powerful, stable machine for demanding ground conditions.\n\nDaily rate: $300. Delivery: $202.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Rogers Hill TX — Delivered to Site", "description": "Renting the Kubota SVL75-2 compact track loader near Rogers Hill TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $202.60.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Bland_eng": [
    {"title": "Mini Excavator Rental Bland TX — $200/Day", "description": "Compact excavator for rent in Bland TX. Delivered to your site.\n\nIdeal for trenching, grading, foundation digging, and land clearing.\n\n$200/day. Delivery to Bland: $203.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Bland TX — Delivery Included", "description": "Need an excavator in Bland? We bring the machine to you.\n\nKubota compact excavator — rubber tracks, blade, great on soft or tight lots.\n\n$200/day + $203.00 delivery to Bland.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Bland TX Excavator Rental — Trenching, Grading & More", "description": "Compact excavator rental serving Bland TX. Perfect for fence lines, utility trenches, pool dig, and drainage.\n\n$200/day. Delivery to Bland: $203.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Bland TX — $200/Day Delivered", "description": "Kubota compact excavator available for Bland TX area. Ideal for residential or light commercial dig work.\n\nRate: $200/day. Delivery: $203.00.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Bland TX Delivery — $200/Day", "description": "Compact excavator rental in Bland TX. Delivered, operated if needed, picked up when done.\n\nUses: trenching, stump removal, grading, demolition.\n\n$200/day + $203.00 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Bland_eng": [
    {"title": "Track Loader Rental Bland TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader available near Bland TX.\n\nPerfect for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Bland: $203.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Bland TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Bland TX. Ideal for rough terrain — more stable than wheeled skid steers.\n\n$300/day. Bland delivery: $203.00.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Bland TX — $300/Day", "description": "Renting the Kubota SVL75-2 compact track loader near Bland TX. We deliver to your job site.\n\n$300/day + $203.00 delivery to Bland.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Bland TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader for rent in Bland TX. Great for grading, hauling, and moving material on residential and commercial sites.\n\nDaily rate: $300. Delivery: $203.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Bland TX — Delivered to Site", "description": "Kubota SVL75-2 compact track loader rental serving Bland TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $203.00.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Flat_eng": [
    {"title": "Mini Excavator Rental Flat TX — $200/Day", "description": "Compact excavator for rent in Flat TX. Delivered direct to your property.\n\nGreat for digging trenches, clearing stumps, grading pads, and excavating foundations.\n\n$200/day. Delivery to Flat: $204.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator Rental Near Flat TX — Delivery Available", "description": "Kubota compact excavator available for Flat TX. We haul it to your site.\n\n$200/day + $204.60 delivery to Flat.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Flat TX Excavator Rental — Trenching, Grading, Land Clearing", "description": "Need a compact excavator in Flat TX? We deliver the machine to you.\n\nUses: drainage, utility lines, stump removal, pool dig, lot clearing.\n\n$200/day. Flat delivery: $204.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Flat TX — $200/Day Delivered", "description": "Compact excavator rental in Flat TX. Rubber tracks, operator-friendly controls, blade included.\n\nRate: $200/day. Delivery: $204.60.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Flat TX Delivery — $200/Day", "description": "Compact excavator available near Flat TX. Delivered to your job site, picked up when finished.\n\n$200/day + $204.60 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Flat_eng": [
    {"title": "Track Loader Rental Flat TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Flat TX.\n\nIdeal for grading pastures, land clearing, loading work, and heavy site prep.\n\n$300/day. Delivery to Flat: $204.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Flat TX — Rent by the Day", "description": "Renting the Kubota SVL75-2 track loader in Flat TX. More grip than wheeled skid steers on soft or uneven ground.\n\n$300/day. Flat delivery: $204.60.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Flat TX — $300/Day", "description": "Need a track loader in Flat TX? We deliver the Kubota SVL75-2 to you.\n\nUses: grading, pushing, loading, demolition, land clearing.\n\n$300/day + $204.60 delivery to Flat.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Flat TX Track Loader Rental — Kubota SVL75-2", "description": "Kubota SVL75-2 track loader for rent in Flat TX. Handles rough terrain, wet ground, and heavy loads.\n\nDaily rate: $300. Delivery: $204.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Flat TX — Delivered to Site", "description": "Compact track loader rental serving Flat TX. Delivered and retrieved on your schedule.\n\n$300/day. Delivery: $204.60.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Belton_eng": [
    {"title": "Mini Excavator Rental Belton TX — $200/Day Delivered", "description": "Compact excavator for rent in Belton TX. Delivered to your site anywhere in the Belton area.\n\nGreat for trenching, foundation digging, drainage, and land clearing.\n\n$200/day. Delivery to Belton: $207.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent in Belton TX — Delivery Available", "description": "Need a compact excavator in Belton? We haul it to you.\n\nKubota compact excavator — perfect for residential dig work, utility lines, stump removal.\n\n$200/day + $207.00 delivery to Belton.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Belton TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in Belton TX. We deliver to your job site and pick it up when you're done.\n\nUses: trenching, grading, pool dig, drainage, clearing.\n\n$200/day. Belton delivery: $207.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Belton TX — $200/Day", "description": "Kubota compact excavator rental serving Belton TX. Rubber tracks, blade, easy to operate.\n\nRate: $200/day. Delivery: $207.00.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Belton TX — $200/Day Delivered to Site", "description": "Compact excavator available for Belton TX. Ideal for light construction and landscaping dig work.\n\n$200/day + $207.00 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Belton_eng": [
    {"title": "Track Loader Rental Belton TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent in Belton TX.\n\nPerfect for grading, land clearing, loading, and heavy site work across Belton and Bell County.\n\n$300/day. Delivery to Belton: $207.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader in Belton TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental serving Belton TX. More stable than wheeled skid steers on rough or wet ground.\n\n$300/day. Belton delivery: $207.00.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent in Belton TX — $300/Day", "description": "Renting the Kubota SVL75-2 compact track loader to Belton TX. We deliver and pick up.\n\n$300/day + $207.00 delivery to Belton.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Belton TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader for rent in Belton TX. Ideal for demanding ground conditions and heavy-duty site prep.\n\nDaily rate: $300. Delivery: $207.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Belton TX — Delivered to Your Site", "description": "Compact track loader rental in Belton TX. Delivered to your site, retrieved on your schedule.\n\n$300/day. Delivery: $207.00.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Leon Junction_eng": [
    {"title": "Mini Excavator Rental Leon Junction TX — $200/Day", "description": "Compact excavator for rent near Leon Junction TX. Delivered to your job site.\n\nIdeal for trenching, utility lines, drainage, stump removal, and grading.\n\n$200/day. Delivery to Leon Junction: $207.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator Rental Near Leon Junction TX — Delivery Available", "description": "Need a compact excavator in Leon Junction? We bring the machine to you.\n\n$200/day + $207.80 delivery to Leon Junction.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Leon Junction TX Excavator Rental — Trenching & Land Clearing", "description": "Compact excavator available for Leon Junction TX. Great for rural lot work, fence line digging, and drainage projects.\n\n$200/day. Delivery: $207.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Leon Junction TX — $200/Day Delivered", "description": "Kubota compact excavator rental in Leon Junction TX. Delivered direct to your site.\n\nRate: $200/day. Delivery: $207.80.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Leon Junction TX — $200/Day Delivered", "description": "Compact excavator rental serving Leon Junction TX and surrounding areas.\n\n$200/day + $207.80 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Leon Junction_eng": [
    {"title": "Track Loader Rental Leon Junction TX — $300/Day", "description": "Kubota SVL75-2 compact track loader for rent near Leon Junction TX.\n\nGreat for grading, clearing pastures, pushing material, and heavy site work.\n\n$300/day. Delivery to Leon Junction: $207.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Leon Junction TX — Rent Daily", "description": "Renting the Kubota SVL75-2 track loader to Leon Junction TX. Better traction than wheeled skid steers on soft or rough ground.\n\n$300/day. Delivery: $207.80.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Leon Junction TX — $300/Day", "description": "Need a track loader near Leon Junction? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $207.80 delivery.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Leon Junction TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental in Leon Junction TX. Handles demanding terrain and heavy loads.\n\nDaily rate: $300. Delivery: $207.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Leon Junction TX — Delivered to Site", "description": "Compact track loader rental serving Leon Junction TX. Delivered and picked up on your timeline.\n\n$300/day. Delivery: $207.80.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Airville_eng": [
    {"title": "Mini Excavator Rental Airville TX — $200/Day Delivered", "description": "Compact excavator for rent in Airville TX. We deliver to your job site.\n\nPerfect for trenching, grading, stump removal, drainage, and land clearing.\n\n$200/day. Delivery to Airville: $207.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Airville TX — Delivery Available", "description": "Kubota compact excavator available for Airville TX. Ideal for residential and rural dig work.\n\n$200/day + $207.80 delivery to Airville.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Airville TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in Airville TX. Delivered to your site and picked up when done.\n\n$200/day. Delivery: $207.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex Near Airville TX — $200/Day", "description": "Kubota compact excavator rental serving Airville TX and nearby areas. Rubber tracks, blade, easy to operate.\n\nRate: $200/day. Delivery: $207.80.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Airville TX — $200/Day Delivered to Site", "description": "Compact excavator available for Airville TX. Delivered to your site on short notice.\n\n$200/day + $207.80 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Airville_eng": [
    {"title": "Track Loader Rental Airville TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Airville TX.\n\nPerfect for grading, land clearing, and heavy-duty site work.\n\n$300/day. Delivery to Airville: $207.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Airville TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Airville TX. Stable, powerful, handles rough terrain.\n\n$300/day. Airville delivery: $207.80.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Airville TX — $300/Day", "description": "Need a track loader in Airville? We deliver the Kubota SVL75-2 to your job site.\n\n$300/day + $207.80 delivery to Airville.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Airville TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader for rent in Airville TX. Great for pasture clearing, material handling, and construction prep.\n\nDaily rate: $300. Delivery: $207.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Airville TX — Delivered to Site", "description": "Compact track loader rental serving Airville TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $207.80.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Gatesville_eng": [
    {"title": "Mini Excavator Rental Gatesville TX — $200/Day Delivered", "description": "Compact excavator for rent in Gatesville TX. Delivered to your site across Coryell County.\n\nGreat for trenching, drainage, foundation work, and land clearing.\n\n$200/day. Delivery to Gatesville: $208.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent in Gatesville TX — Delivery Available", "description": "Need a compact excavator in Gatesville? We bring it to you.\n\nKubota compact excavator — rubber tracks, blade, handles tight spots.\n\n$200/day + $208.60 delivery to Gatesville.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Gatesville TX Excavator Rental — Trenching, Grading, Clearing", "description": "Compact excavator rental serving Gatesville TX. Ideal for rural lots, fence lines, utility work, and site prep.\n\n$200/day. Gatesville delivery: $208.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Gatesville TX — $200/Day", "description": "Kubota compact excavator rental in Gatesville TX. Delivered to your site and picked up when done.\n\nRate: $200/day. Delivery: $208.60.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Gatesville TX — $200/Day Delivered to Site", "description": "Compact excavator available for Gatesville TX and the surrounding Coryell County area.\n\n$200/day + $208.60 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Gatesville_eng": [
    {"title": "Track Loader Rental Gatesville TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent in Gatesville TX.\n\nIdeal for ranch work, grading, land clearing, and heavy site prep in Coryell County.\n\n$300/day. Delivery to Gatesville: $208.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader in Gatesville TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental serving Gatesville TX. Better traction than wheeled machines on rough or wet terrain.\n\n$300/day. Gatesville delivery: $208.60.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Gatesville TX — $300/Day", "description": "Renting the Kubota SVL75-2 compact track loader to Gatesville TX. We deliver and pick up.\n\n$300/day + $208.60 delivery to Gatesville.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Gatesville TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental in Gatesville TX. Perfect for ranch operations, grading, and construction site work.\n\nDaily rate: $300. Delivery: $208.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Gatesville TX — Delivered to Your Site", "description": "Compact track loader rental serving Gatesville TX. Delivered and retrieved on your schedule.\n\n$300/day. Delivery: $208.60.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Academy_eng": [
    {"title": "Mini Excavator Rental Academy TX — $200/Day Delivered", "description": "Compact excavator for rent in Academy TX. Delivered to your property.\n\nPerfect for trenching, utility lines, pool excavation, stump removal, and grading.\n\n$200/day. Delivery to Academy: $209.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Academy TX — Delivery Available", "description": "Need a compact excavator in Academy TX? We haul it to your site.\n\n$200/day + $209.00 delivery to Academy.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Academy TX Excavator Rental — Trenching, Grading & More", "description": "Compact excavator rental in Academy TX. Delivered and picked up from your site.\n\nUses: trenching, drainage, foundation work, land clearing.\n\n$200/day. Delivery: $209.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Academy TX — $200/Day", "description": "Kubota compact excavator rental serving Academy TX. Rubber tracks, blade, easy controls.\n\nRate: $200/day. Delivery: $209.00.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Academy TX — $200/Day Delivered to Site", "description": "Compact excavator available for Academy TX. We deliver and pick up on your schedule.\n\n$200/day + $209.00 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Academy_eng": [
    {"title": "Track Loader Rental Academy TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Academy TX.\n\nIdeal for grading, clearing, loading, and heavy construction prep.\n\n$300/day. Delivery to Academy: $209.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Academy TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Academy TX. Handles rough or wet terrain better than wheeled skid steers.\n\n$300/day. Academy delivery: $209.00.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Academy TX — $300/Day", "description": "Need a track loader in Academy TX? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $209.00 delivery to Academy.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Academy TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader for rent in Academy TX. Powerful and stable for demanding work.\n\nDaily rate: $300. Delivery: $209.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Academy TX — Delivered to Your Site", "description": "Compact track loader rental serving Academy TX. Delivered and picked up on your timeline.\n\n$300/day. Delivery: $209.00.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Mount Calm_eng": [
    {"title": "Mini Excavator Rental Mount Calm TX — $200/Day Delivered", "description": "Compact excavator for rent in Mount Calm TX. Delivered to your property.\n\nGreat for trenching, drainage, stump removal, and grading.\n\n$200/day. Delivery to Mount Calm: $209.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Mount Calm TX — Delivery Available", "description": "Need a compact excavator in Mount Calm? We haul it to your site.\n\n$200/day + $209.00 delivery to Mount Calm.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mount Calm TX Excavator Rental — Trenching, Grading, Clearing", "description": "Compact excavator rental in Mount Calm TX. Kubota machine on rubber tracks — handles tight rural lots and fence lines.\n\n$200/day. Delivery: $209.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Mount Calm TX — $200/Day", "description": "Kubota compact excavator rental serving Mount Calm TX. Delivered and picked up on your schedule.\n\nRate: $200/day. Delivery: $209.00.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Mount Calm TX — $200/Day Delivered to Site", "description": "Compact excavator available for Mount Calm TX and surrounding areas.\n\n$200/day + $209.00 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Mount Calm_eng": [
    {"title": "Track Loader Rental Mount Calm TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Mount Calm TX.\n\nIdeal for pasture clearing, grading, and heavy site work in rural Hill County.\n\n$300/day. Delivery to Mount Calm: $209.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Mount Calm TX — Rent Daily", "description": "Kubota SVL75-2 track loader rental in Mount Calm TX. Better traction on rough or soft terrain than wheeled machines.\n\n$300/day. Mount Calm delivery: $209.00.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Mount Calm TX — $300/Day", "description": "Need a track loader in Mount Calm? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $209.00 delivery to Mount Calm.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mount Calm TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader for rent in Mount Calm TX. Handles tough ground and heavy loads.\n\nDaily rate: $300. Delivery: $209.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Mount Calm TX — Delivered to Site", "description": "Compact track loader rental serving Mount Calm TX. Delivered and retrieved on your timeline.\n\n$300/day. Delivery: $209.00.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Cayote_eng": [
    {"title": "Mini Excavator Rental Cayote TX — $200/Day Delivered", "description": "Compact excavator for rent near Cayote TX. Delivered to your job site.\n\nPerfect for trenching, grading, utility work, stump removal, and land clearing.\n\n$200/day. Delivery to Cayote: $209.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Cayote TX — Delivery Available", "description": "Kubota compact excavator available for Cayote TX. We bring the machine to you.\n\n$200/day + $209.80 delivery to Cayote.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Cayote TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in Cayote TX. Ideal for rural lot work and light construction projects.\n\n$200/day. Delivery: $209.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Cayote TX — $200/Day", "description": "Kubota compact excavator rental serving Cayote TX. Delivered and picked up from your site.\n\nRate: $200/day. Delivery: $209.80.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Cayote TX — $200/Day Delivered to Site", "description": "Compact excavator available for Cayote TX and surrounding areas.\n\n$200/day + $209.80 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Cayote_eng": [
    {"title": "Track Loader Rental Cayote TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Cayote TX.\n\nGreat for grading, clearing, and heavy-duty site work.\n\n$300/day. Delivery to Cayote: $209.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Cayote TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Cayote TX. More traction than wheeled skid steers on rough terrain.\n\n$300/day. Cayote delivery: $209.80.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Cayote TX — $300/Day", "description": "Need a track loader in Cayote TX? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $209.80 delivery to Cayote.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Cayote TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental in Cayote TX. Handles tough ground conditions and heavy loads.\n\nDaily rate: $300. Delivery: $209.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Cayote TX — Delivered to Site", "description": "Compact track loader rental serving Cayote TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $209.80.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ]
}
with open("data/batch_temp.json", "w") as f:
    json.dump(batch10, f, indent=2)
print(f"Written {len(batch10)} slots to batch_temp.json")
