import json
batch11 = {
  "mini-ex_Westcliff_eng": [
    {"title": "Mini Excavator Rental Westcliff TX — $200/Day Delivered", "description": "Compact excavator for rent near Westcliff TX. Delivered to your job site.\n\nGreat for trenching, grading, drainage, stump removal, and land clearing.\n\n$200/day. Delivery to Westcliff: $210.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Westcliff TX — Delivery Available", "description": "Kubota compact excavator available for Westcliff TX. We haul it to your site.\n\n$200/day + $210.20 delivery to Westcliff.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Westcliff TX Excavator Rental — Trenching, Grading & More", "description": "Compact excavator rental in Westcliff TX. Delivered and picked up on your schedule.\n\nUses: utility lines, drainage, pool dig, foundation work.\n\n$200/day. Delivery: $210.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Westcliff TX — $200/Day", "description": "Kubota compact excavator rental serving Westcliff TX. Rubber tracks, blade, easy controls.\n\nRate: $200/day. Delivery: $210.20.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Westcliff TX — $200/Day Delivered to Site", "description": "Compact excavator available for Westcliff TX and surrounding areas.\n\n$200/day + $210.20 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Westcliff_eng": [
    {"title": "Track Loader Rental Westcliff TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Westcliff TX.\n\nIdeal for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Westcliff: $210.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Westcliff TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Westcliff TX. More traction than wheeled skid steers on rough terrain.\n\n$300/day. Westcliff delivery: $210.20.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Westcliff TX — $300/Day", "description": "Need a track loader in Westcliff TX? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $210.20 delivery to Westcliff.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Westcliff TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader for rent near Westcliff TX. Handles rough ground and heavy loads.\n\nDaily rate: $300. Delivery: $210.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Westcliff TX — Delivered to Site", "description": "Compact track loader rental serving Westcliff TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $210.20.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Lott_eng": [
    {"title": "Mini Excavator Rental Lott TX — $200/Day Delivered", "description": "Compact excavator for rent in Lott TX. Delivered to your job site in Falls County.\n\nPerfect for trenching, drainage, stump removal, grading, and land clearing.\n\n$200/day. Delivery to Lott: $211.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator Rental Near Lott TX — Delivery Available", "description": "Need a compact excavator in Lott? We bring the machine to you.\n\n$200/day + $211.80 delivery to Lott.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Lott TX Excavator Rental — Trenching, Grading, Clearing", "description": "Compact excavator rental serving Lott TX. Ideal for rural lots, fence lines, utility work, and foundation digging.\n\n$200/day. Delivery: $211.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Lott TX — $200/Day", "description": "Kubota compact excavator rental in Lott TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $211.80.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Lott TX — $200/Day Delivered to Site", "description": "Compact excavator available for Lott TX and the surrounding Falls County area.\n\n$200/day + $211.80 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Lott_eng": [
    {"title": "Track Loader Rental Lott TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent in Lott TX.\n\nGreat for grading pastures, clearing brush, loading, and construction site work.\n\n$300/day. Delivery to Lott: $211.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Lott TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Lott TX. Better stability than wheeled skid steers on soft or uneven ground.\n\n$300/day. Lott delivery: $211.80.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Lott TX — $300/Day", "description": "Need a track loader in Lott TX? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $211.80 delivery to Lott.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Lott TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental in Lott TX. Powerful, stable machine for demanding ground conditions.\n\nDaily rate: $300. Delivery: $211.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Lott TX — Delivered to Your Site", "description": "Compact track loader rental serving Lott TX. Delivered and retrieved on your schedule.\n\n$300/day. Delivery: $211.80.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Birome_eng": [
    {"title": "Mini Excavator Rental Birome TX — $200/Day Delivered", "description": "Compact excavator for rent near Birome TX. Delivered to your property.\n\nIdeal for trenching, grading, fence line digging, stump removal, and drainage.\n\n$200/day. Delivery to Birome: $211.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Birome TX — Delivery Available", "description": "Kubota compact excavator available for Birome TX. We haul it to your site.\n\n$200/day + $211.80 delivery to Birome.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Birome TX Excavator Rental — Trenching & Land Clearing", "description": "Compact excavator rental in Birome TX. Kubota machine on rubber tracks — handles rural lots with ease.\n\n$200/day. Delivery: $211.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Birome TX — $200/Day", "description": "Kubota compact excavator rental serving Birome TX. Delivered and picked up from your site.\n\nRate: $200/day. Delivery: $211.80.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Birome TX — $200/Day Delivered to Site", "description": "Compact excavator available for Birome TX and surrounding Hill County areas.\n\n$200/day + $211.80 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Birome_eng": [
    {"title": "Track Loader Rental Birome TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Birome TX.\n\nPerfect for grading, clearing brush, pushing material, and site prep.\n\n$300/day. Delivery to Birome: $211.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Birome TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Birome TX. More traction than wheeled skid steers on soft or rough ground.\n\n$300/day. Birome delivery: $211.80.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Birome TX — $300/Day", "description": "Need a track loader near Birome? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $211.80 delivery to Birome.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Birome TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Birome TX. Handles tough terrain and heavy loads with ease.\n\nDaily rate: $300. Delivery: $211.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Birome TX — Delivered to Site", "description": "Compact track loader rental serving Birome TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $211.80.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Mosheim_eng": [
    {"title": "Mini Excavator Rental Mosheim TX — $200/Day Delivered", "description": "Compact excavator for rent near Mosheim TX. Delivered to your job site.\n\nPerfect for trenching, grading, drainage, stump removal, and land clearing.\n\n$200/day. Delivery to Mosheim: $212.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator Rental Near Mosheim TX — Delivery Available", "description": "Need a compact excavator in Mosheim? We haul it to you.\n\n$200/day + $212.20 delivery to Mosheim.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mosheim TX Excavator Rental — Trenching, Grading, Clearing", "description": "Compact excavator rental in Mosheim TX. Ideal for fence lines, utility work, and residential dig projects.\n\n$200/day. Delivery: $212.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Mosheim TX — $200/Day", "description": "Kubota compact excavator rental serving Mosheim TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $212.20.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Mosheim TX — $200/Day Delivered to Site", "description": "Compact excavator available for Mosheim TX and surrounding Bosque County areas.\n\n$200/day + $212.20 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Mosheim_eng": [
    {"title": "Track Loader Rental Mosheim TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Mosheim TX.\n\nGreat for grading, clearing, loading, and heavy site work in Bosque County.\n\n$300/day. Delivery to Mosheim: $212.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Mosheim TX — Rent Daily", "description": "Kubota SVL75-2 track loader rental in Mosheim TX. Stable on rough and soft terrain.\n\n$300/day. Mosheim delivery: $212.20.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Mosheim TX — $300/Day", "description": "Need a track loader near Mosheim? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $212.20 delivery to Mosheim.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mosheim TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader for rent near Mosheim TX. Handles demanding ground conditions and heavy loads.\n\nDaily rate: $300. Delivery: $212.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Mosheim TX — Delivered to Site", "description": "Compact track loader rental serving Mosheim TX. Delivered and retrieved on your timeline.\n\n$300/day. Delivery: $212.20.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Ocker_eng": [
    {"title": "Mini Excavator Rental Ocker TX — $200/Day Delivered", "description": "Compact excavator for rent near Ocker TX. Delivered to your job site.\n\nGreat for trenching, grading, utility work, stump removal, and land clearing.\n\n$200/day. Delivery to Ocker: $213.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Ocker TX — Delivery Available", "description": "Kubota compact excavator available for Ocker TX. We haul it to your site.\n\n$200/day + $213.00 delivery to Ocker.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Ocker TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in Ocker TX. Perfect for rural lot work and light construction.\n\n$200/day. Delivery: $213.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Ocker TX — $200/Day", "description": "Kubota compact excavator rental serving Ocker TX. Delivered and picked up from your site.\n\nRate: $200/day. Delivery: $213.00.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Ocker TX — $200/Day Delivered to Site", "description": "Compact excavator available for Ocker TX and nearby areas.\n\n$200/day + $213.00 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Ocker_eng": [
    {"title": "Track Loader Rental Ocker TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Ocker TX.\n\nIdeal for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Ocker: $213.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Ocker TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Ocker TX. More traction than wheeled skid steers on rough terrain.\n\n$300/day. Ocker delivery: $213.00.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Ocker TX — $300/Day", "description": "Need a track loader near Ocker TX? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $213.00 delivery to Ocker.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Ocker TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Ocker TX. Handles tough ground conditions and heavy loads.\n\nDaily rate: $300. Delivery: $213.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Ocker TX — Delivered to Site", "description": "Compact track loader rental serving Ocker TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $213.00.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Little River_eng": [
    {"title": "Mini Excavator Rental Little River TX — $200/Day Delivered", "description": "Compact excavator for rent in Little River TX. Delivered to your job site in Bell County.\n\nPerfect for trenching, drainage, grading, stump removal, and land clearing.\n\n$200/day. Delivery to Little River: $213.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator Rental Near Little River TX — Delivery Available", "description": "Need a compact excavator in Little River? We bring the machine to you.\n\n$200/day + $213.40 delivery to Little River.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Little River TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental serving Little River TX. Ideal for residential and rural dig work.\n\n$200/day. Delivery: $213.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Little River TX — $200/Day", "description": "Kubota compact excavator rental in Little River TX. Rubber tracks, blade, easy to operate.\n\nRate: $200/day. Delivery: $213.40.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Little River TX — $200/Day Delivered to Site", "description": "Compact excavator available for Little River TX and surrounding Bell County areas.\n\n$200/day + $213.40 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Little River_eng": [
    {"title": "Track Loader Rental Little River TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent in Little River TX.\n\nGreat for grading, clearing, loading, and construction site work in Bell County.\n\n$300/day. Delivery to Little River: $213.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Little River TX — Rent Daily", "description": "Kubota SVL75-2 track loader rental in Little River TX. Stable on rough or soft terrain.\n\n$300/day. Little River delivery: $213.40.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Little River TX — $300/Day", "description": "Need a track loader in Little River TX? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $213.40 delivery to Little River.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Little River TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader for rent in Little River TX. Powerful, stable machine for demanding work.\n\nDaily rate: $300. Delivery: $213.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Little River TX — Delivered to Site", "description": "Compact track loader rental serving Little River TX. Delivered and retrieved on your schedule.\n\n$300/day. Delivery: $213.40.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Little River-Academy_eng": [
    {"title": "Mini Excavator Rental Little River-Academy TX — $200/Day", "description": "Compact excavator for rent in Little River-Academy TX. Delivered to your property.\n\nGreat for trenching, grading, utility work, drainage, and land clearing.\n\n$200/day. Delivery to Little River-Academy: $213.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator Rental Near Little River-Academy TX — Delivery Available", "description": "Need a compact excavator in Little River-Academy? We haul it to your site.\n\n$200/day + $213.40 delivery to Little River-Academy.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Little River-Academy TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in Little River-Academy TX. Kubota machine on rubber tracks — handles all types of dig work.\n\n$200/day. Delivery: $213.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Little River-Academy TX — $200/Day", "description": "Kubota compact excavator rental serving Little River-Academy TX. Delivered and picked up from your site.\n\nRate: $200/day. Delivery: $213.40.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Little River-Academy TX — $200/Day Delivered", "description": "Compact excavator available for Little River-Academy TX area.\n\n$200/day + $213.40 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Little River-Academy_eng": [
    {"title": "Track Loader Rental Little River-Academy TX — $300/Day", "description": "Kubota SVL75-2 compact track loader for rent in Little River-Academy TX.\n\nIdeal for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Little River-Academy: $213.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Little River-Academy TX — Rent Daily", "description": "Kubota SVL75-2 track loader rental in Little River-Academy TX. More traction than wheeled machines on rough terrain.\n\n$300/day. Delivery: $213.40.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Little River-Academy TX — $300/Day", "description": "Need a track loader in Little River-Academy? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $213.40 delivery.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Little River-Academy TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental in Little River-Academy TX. Handles tough terrain and heavy loads.\n\nDaily rate: $300. Delivery: $213.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Little River-Academy TX — Delivered to Site", "description": "Compact track loader rental serving Little River-Academy TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $213.40.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Zabcikville_eng": [
    {"title": "Mini Excavator Rental Zabcikville TX — $200/Day Delivered", "description": "Compact excavator for rent near Zabcikville TX. Delivered to your job site.\n\nPerfect for trenching, grading, utility work, stump removal, and land clearing.\n\n$200/day. Delivery to Zabcikville: $213.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Zabcikville TX — Delivery Available", "description": "Kubota compact excavator available for Zabcikville TX. We bring the machine to you.\n\n$200/day + $213.80 delivery to Zabcikville.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Zabcikville TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in Zabcikville TX. Ideal for rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $213.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Zabcikville TX — $200/Day", "description": "Kubota compact excavator rental serving Zabcikville TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $213.80.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Zabcikville TX — $200/Day Delivered to Site", "description": "Compact excavator available for Zabcikville TX and nearby Bell County areas.\n\n$200/day + $213.80 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Zabcikville_eng": [
    {"title": "Track Loader Rental Zabcikville TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Zabcikville TX.\n\nGreat for grading, clearing brush, loading material, and construction prep.\n\n$300/day. Delivery to Zabcikville: $213.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Zabcikville TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Zabcikville TX. Stable and powerful on rough terrain.\n\n$300/day. Zabcikville delivery: $213.80.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Zabcikville TX — $300/Day", "description": "Need a track loader near Zabcikville? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $213.80 delivery to Zabcikville.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Zabcikville TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Zabcikville TX. Handles demanding terrain and heavy loads.\n\nDaily rate: $300. Delivery: $213.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Zabcikville TX — Delivered to Site", "description": "Compact track loader rental serving Zabcikville TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $213.80.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Rocky Hill_eng": [
    {"title": "Mini Excavator Rental Rocky Hill TX — $200/Day Delivered", "description": "Compact excavator for rent near Rocky Hill TX. Delivered to your job site.\n\nIdeal for trenching, grading, stump removal, drainage, and land clearing.\n\n$200/day. Delivery to Rocky Hill: $214.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Rocky Hill TX — Delivery Available", "description": "Need a compact excavator in Rocky Hill TX? We haul it to your site.\n\n$200/day + $214.20 delivery to Rocky Hill.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rocky Hill TX Excavator Rental — Trenching & Land Clearing", "description": "Compact excavator rental in Rocky Hill TX. Handles rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $214.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Rocky Hill TX — $200/Day", "description": "Kubota compact excavator rental serving Rocky Hill TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $214.20.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Rocky Hill TX — $200/Day Delivered to Site", "description": "Compact excavator available for Rocky Hill TX and nearby areas.\n\n$200/day + $214.20 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Rocky Hill_eng": [
    {"title": "Track Loader Rental Rocky Hill TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Rocky Hill TX.\n\nPerfect for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Rocky Hill: $214.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Rocky Hill TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Rocky Hill TX. More traction than wheeled skid steers on rough terrain.\n\n$300/day. Rocky Hill delivery: $214.20.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Rocky Hill TX — $300/Day", "description": "Need a track loader near Rocky Hill TX? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $214.20 delivery to Rocky Hill.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rocky Hill TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Rocky Hill TX. Handles tough ground conditions and heavy loads.\n\nDaily rate: $300. Delivery: $214.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Rocky Hill TX — Delivered to Site", "description": "Compact track loader rental serving Rocky Hill TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $214.20.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Prairie Hill_eng": [
    {"title": "Mini Excavator Rental Prairie Hill TX — $200/Day Delivered", "description": "Compact excavator for rent in Prairie Hill TX. Delivered to your job site.\n\nGreat for trenching, grading, utility lines, stump removal, and drainage.\n\n$200/day. Delivery to Prairie Hill: $214.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator Rental Near Prairie Hill TX — Delivery Available", "description": "Need a compact excavator in Prairie Hill? We bring the machine to you.\n\n$200/day + $214.20 delivery to Prairie Hill.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Prairie Hill TX Excavator Rental — Trenching, Grading & More", "description": "Compact excavator rental serving Prairie Hill TX. Ideal for rural lot work, fence lines, and light construction.\n\n$200/day. Delivery: $214.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Prairie Hill TX — $200/Day", "description": "Kubota compact excavator rental in Prairie Hill TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $214.20.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Prairie Hill TX — $200/Day Delivered to Site", "description": "Compact excavator available for Prairie Hill TX and surrounding Limestone County areas.\n\n$200/day + $214.20 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Prairie Hill_eng": [
    {"title": "Track Loader Rental Prairie Hill TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Prairie Hill TX.\n\nIdeal for grading, clearing brush, loading material, and heavy site work.\n\n$300/day. Delivery to Prairie Hill: $214.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Prairie Hill TX — Rent Daily", "description": "Kubota SVL75-2 track loader rental in Prairie Hill TX. Stable on rough and soft terrain.\n\n$300/day. Prairie Hill delivery: $214.20.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Prairie Hill TX — $300/Day", "description": "Need a track loader in Prairie Hill TX? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $214.20 delivery to Prairie Hill.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Prairie Hill TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental in Prairie Hill TX. Handles demanding ground and heavy loads.\n\nDaily rate: $300. Delivery: $214.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Prairie Hill TX — Delivered to Your Site", "description": "Compact track loader rental serving Prairie Hill TX. Delivered and retrieved on your schedule.\n\n$300/day. Delivery: $214.20.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ]
}
with open("data/batch_temp.json", "w") as f:
    json.dump(batch11, f, indent=2)
print(f"Written {len(batch11)} slots to batch_temp.json")
