import json
batch12 = {
  "mini-ex_Otto_eng": [
    {"title": "Mini Excavator Rental Otto TX — $200/Day Delivered", "description": "Compact excavator for rent near Otto TX. Delivered to your job site.\n\nGreat for trenching, grading, utility lines, stump removal, and land clearing.\n\n$200/day. Delivery to Otto: $215.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Otto TX — Delivery Available", "description": "Kubota compact excavator available for Otto TX. We haul it to your site.\n\n$200/day + $215.80 delivery to Otto.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Otto TX Excavator Rental — Trenching, Grading & More", "description": "Compact excavator rental in Otto TX. Ideal for rural lot work, fence lines, and drainage projects.\n\n$200/day. Delivery: $215.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Otto TX — $200/Day", "description": "Kubota compact excavator rental serving Otto TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $215.80.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Otto TX — $200/Day Delivered to Site", "description": "Compact excavator available for Otto TX and surrounding areas.\n\n$200/day + $215.80 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Otto_eng": [
    {"title": "Track Loader Rental Otto TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Otto TX.\n\nIdeal for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Otto: $215.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Otto TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Otto TX. More traction than wheeled skid steers on rough or wet terrain.\n\n$300/day. Otto delivery: $215.80.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Otto TX — $300/Day", "description": "Need a track loader near Otto TX? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $215.80 delivery to Otto.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Otto TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Otto TX. Handles tough terrain and heavy loads.\n\nDaily rate: $300. Delivery: $215.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Otto TX — Delivered to Site", "description": "Compact track loader rental serving Otto TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $215.80.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Cedar Springs_eng": [
    {"title": "Mini Excavator Rental Cedar Springs TX — $200/Day Delivered", "description": "Compact excavator for rent near Cedar Springs TX. Delivered to your property.\n\nPerfect for trenching, grading, drainage, stump removal, and land clearing.\n\n$200/day. Delivery to Cedar Springs: $217.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator Rental Near Cedar Springs TX — Delivery Available", "description": "Kubota compact excavator available for Cedar Springs TX. We haul it to your site.\n\n$200/day + $217.00 delivery to Cedar Springs.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Cedar Springs TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in Cedar Springs TX. Handles rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $217.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Cedar Springs TX — $200/Day", "description": "Kubota compact excavator rental serving Cedar Springs TX. Delivered and picked up from your site.\n\nRate: $200/day. Delivery: $217.00.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Cedar Springs TX — $200/Day Delivered to Site", "description": "Compact excavator available for Cedar Springs TX and surrounding areas.\n\n$200/day + $217.00 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Cedar Springs_eng": [
    {"title": "Track Loader Rental Cedar Springs TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Cedar Springs TX.\n\nGreat for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Cedar Springs: $217.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Cedar Springs TX — Rent Daily", "description": "Kubota SVL75-2 track loader rental in Cedar Springs TX. Stable on rough and soft terrain.\n\n$300/day. Cedar Springs delivery: $217.00.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Cedar Springs TX — $300/Day", "description": "Need a track loader near Cedar Springs? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $217.00 delivery to Cedar Springs.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Cedar Springs TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader for rent near Cedar Springs TX. Handles tough terrain and heavy loads.\n\nDaily rate: $300. Delivery: $217.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Cedar Springs TX — Delivered to Site", "description": "Compact track loader rental serving Cedar Springs TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $217.00.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Abbott_eng": [
    {"title": "Mini Excavator Rental Abbott TX — $200/Day Delivered", "description": "Compact excavator for rent in Abbott TX. Delivered to your job site in Hill County.\n\nGreat for trenching, grading, drainage, stump removal, and land clearing.\n\n$200/day. Delivery to Abbott: $219.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent in Abbott TX — Delivery Available", "description": "Need a compact excavator in Abbott? We bring the machine to you.\n\n$200/day + $219.00 delivery to Abbott.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Abbott TX Excavator Rental — Trenching, Grading & Clearing", "description": "Compact excavator rental serving Abbott TX. Ideal for rural lots, utility work, and construction prep.\n\n$200/day. Delivery: $219.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Abbott TX — $200/Day", "description": "Kubota compact excavator rental in Abbott TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $219.00.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Abbott TX — $200/Day Delivered to Site", "description": "Compact excavator available for Abbott TX and the surrounding Hill County area.\n\n$200/day + $219.00 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Abbott_eng": [
    {"title": "Track Loader Rental Abbott TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent in Abbott TX.\n\nPerfect for grading, clearing brush, loading, and heavy site prep in Hill County.\n\n$300/day. Delivery to Abbott: $219.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Abbott TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Abbott TX. Better traction than wheeled machines on rough terrain.\n\n$300/day. Abbott delivery: $219.00.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Abbott TX — $300/Day", "description": "Need a track loader in Abbott TX? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $219.00 delivery to Abbott.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Abbott TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader for rent in Abbott TX. Handles demanding terrain and heavy loads.\n\nDaily rate: $300. Delivery: $219.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Abbott TX — Delivered to Your Site", "description": "Compact track loader rental serving Abbott TX. Delivered and retrieved on your schedule.\n\n$300/day. Delivery: $219.00.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Cyclone_eng": [
    {"title": "Mini Excavator Rental Cyclone TX — $200/Day Delivered", "description": "Compact excavator for rent near Cyclone TX. Delivered to your job site.\n\nIdeal for trenching, grading, stump removal, drainage, and land clearing.\n\n$200/day. Delivery to Cyclone: $221.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Cyclone TX — Delivery Available", "description": "Kubota compact excavator available for Cyclone TX. We haul it to your site.\n\n$200/day + $221.80 delivery to Cyclone.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Cyclone TX Excavator Rental — Trenching & Land Clearing", "description": "Compact excavator rental in Cyclone TX. Handles rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $221.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Cyclone TX — $200/Day", "description": "Kubota compact excavator rental serving Cyclone TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $221.80.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Cyclone TX — $200/Day Delivered to Site", "description": "Compact excavator available for Cyclone TX and surrounding areas.\n\n$200/day + $221.80 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Cyclone_eng": [
    {"title": "Track Loader Rental Cyclone TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Cyclone TX.\n\nGreat for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Cyclone: $221.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Cyclone TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Cyclone TX. More traction than wheeled skid steers on rough terrain.\n\n$300/day. Cyclone delivery: $221.80.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Cyclone TX — $300/Day", "description": "Need a track loader near Cyclone? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $221.80 delivery to Cyclone.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Cyclone TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Cyclone TX. Handles tough ground conditions and heavy loads.\n\nDaily rate: $300. Delivery: $221.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Cyclone TX — Delivered to Site", "description": "Compact track loader rental serving Cyclone TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $221.80.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Clifton_eng": [
    {"title": "Mini Excavator Rental Clifton TX — $200/Day Delivered", "description": "Compact excavator for rent in Clifton TX. Delivered to your job site in Bosque County.\n\nGreat for trenching, drainage, grading, stump removal, and land clearing.\n\n$200/day. Delivery to Clifton: $223.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent in Clifton TX — Delivery Available", "description": "Need a compact excavator in Clifton? We bring the machine to you.\n\n$200/day + $223.00 delivery to Clifton.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Clifton TX Excavator Rental — Trenching, Grading & Clearing", "description": "Compact excavator rental serving Clifton TX and Bosque County. Ideal for rural properties, utility lines, and construction prep.\n\n$200/day. Delivery: $223.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Clifton TX — $200/Day", "description": "Kubota compact excavator rental in Clifton TX. Delivered and picked up from your site.\n\nRate: $200/day. Delivery: $223.00.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Clifton TX — $200/Day Delivered to Site", "description": "Compact excavator available for Clifton TX and the broader Bosque County area.\n\n$200/day + $223.00 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Clifton_eng": [
    {"title": "Track Loader Rental Clifton TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent in Clifton TX.\n\nPerfect for ranch work, grading, clearing brush, and heavy site prep in Bosque County.\n\n$300/day. Delivery to Clifton: $223.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader in Clifton TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental serving Clifton TX. Stable and powerful on rough terrain.\n\n$300/day. Clifton delivery: $223.00.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Clifton TX — $300/Day", "description": "Renting the Kubota SVL75-2 track loader to Clifton TX. We deliver and pick up.\n\n$300/day + $223.00 delivery to Clifton.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Clifton TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader for rent in Clifton TX. Handles demanding ground and heavy loads across Bosque County.\n\nDaily rate: $300. Delivery: $223.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Clifton TX — Delivered to Your Site", "description": "Compact track loader rental serving Clifton TX. Delivered and retrieved on your schedule.\n\n$300/day. Delivery: $223.00.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_McClanahan_eng": [
    {"title": "Mini Excavator Rental McClanahan TX — $200/Day Delivered", "description": "Compact excavator for rent near McClanahan TX. Delivered to your property.\n\nIdeal for trenching, grading, utility work, stump removal, and land clearing.\n\n$200/day. Delivery to McClanahan: $225.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator Rental Near McClanahan TX — Delivery Available", "description": "Kubota compact excavator available for McClanahan TX. We haul it to your site.\n\n$200/day + $225.40 delivery to McClanahan.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "McClanahan TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in McClanahan TX. Perfect for rural lot work and light construction.\n\n$200/day. Delivery: $225.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in McClanahan TX — $200/Day", "description": "Kubota compact excavator rental serving McClanahan TX. Delivered and picked up from your site.\n\nRate: $200/day. Delivery: $225.40.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — McClanahan TX — $200/Day Delivered to Site", "description": "Compact excavator available for McClanahan TX and nearby areas.\n\n$200/day + $225.40 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_McClanahan_eng": [
    {"title": "Track Loader Rental McClanahan TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near McClanahan TX.\n\nGreat for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to McClanahan: $225.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near McClanahan TX — Rent Daily", "description": "Kubota SVL75-2 track loader rental in McClanahan TX. Handles rough terrain better than wheeled skid steers.\n\n$300/day. McClanahan delivery: $225.40.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — McClanahan TX — $300/Day", "description": "Need a track loader near McClanahan? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $225.40 delivery to McClanahan.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "McClanahan TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near McClanahan TX. Handles tough ground conditions and heavy loads.\n\nDaily rate: $300. Delivery: $225.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — McClanahan TX — Delivered to Site", "description": "Compact track loader rental serving McClanahan TX. Delivered and picked up on your timeline.\n\n$300/day. Delivery: $225.40.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Red Ranger_eng": [
    {"title": "Mini Excavator Rental Red Ranger TX — $200/Day Delivered", "description": "Compact excavator for rent near Red Ranger TX. Delivered to your job site.\n\nPerfect for trenching, grading, utility lines, stump removal, and land clearing.\n\n$200/day. Delivery to Red Ranger: $225.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Red Ranger TX — Delivery Available", "description": "Kubota compact excavator available for Red Ranger TX. We haul it to your site.\n\n$200/day + $225.40 delivery to Red Ranger.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Red Ranger TX Excavator Rental — Trenching & Land Clearing", "description": "Compact excavator rental in Red Ranger TX. Handles rural lots, fence lines, and utility trenching.\n\n$200/day. Delivery: $225.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Red Ranger TX — $200/Day", "description": "Kubota compact excavator rental serving Red Ranger TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $225.40.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Red Ranger TX — $200/Day Delivered to Site", "description": "Compact excavator available for Red Ranger TX and surrounding areas.\n\n$200/day + $225.40 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Red Ranger_eng": [
    {"title": "Track Loader Rental Red Ranger TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Red Ranger TX.\n\nIdeal for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Red Ranger: $225.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Red Ranger TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Red Ranger TX. More traction than wheeled machines on rough terrain.\n\n$300/day. Red Ranger delivery: $225.40.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Red Ranger TX — $300/Day", "description": "Need a track loader near Red Ranger TX? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $225.40 delivery to Red Ranger.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Red Ranger TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Red Ranger TX. Handles demanding ground conditions and heavy loads.\n\nDaily rate: $300. Delivery: $225.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Red Ranger TX — Delivered to Site", "description": "Compact track loader rental serving Red Ranger TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $225.40.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Ben Hur_eng": [
    {"title": "Mini Excavator Rental Ben Hur TX — $200/Day Delivered", "description": "Compact excavator for rent near Ben Hur TX. Delivered to your property.\n\nGreat for trenching, grading, stump removal, drainage, and land clearing.\n\n$200/day. Delivery to Ben Hur: $225.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Ben Hur TX — Delivery Available", "description": "Kubota compact excavator available for Ben Hur TX. We bring the machine to you.\n\n$200/day + $225.40 delivery to Ben Hur.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Ben Hur TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in Ben Hur TX. Ideal for rural lot work and light construction projects.\n\n$200/day. Delivery: $225.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Ben Hur TX — $200/Day", "description": "Kubota compact excavator rental serving Ben Hur TX. Delivered and picked up from your site.\n\nRate: $200/day. Delivery: $225.40.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Ben Hur TX — $200/Day Delivered to Site", "description": "Compact excavator available for Ben Hur TX and nearby areas.\n\n$200/day + $225.40 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Ben Hur_eng": [
    {"title": "Track Loader Rental Ben Hur TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Ben Hur TX.\n\nPerfect for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Ben Hur: $225.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Ben Hur TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Ben Hur TX. Stable on rough and soft terrain.\n\n$300/day. Ben Hur delivery: $225.40.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Ben Hur TX — $300/Day", "description": "Need a track loader near Ben Hur? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $225.40 delivery to Ben Hur.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Ben Hur TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Ben Hur TX. Handles tough terrain and heavy loads.\n\nDaily rate: $300. Delivery: $225.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Ben Hur TX — Delivered to Site", "description": "Compact track loader rental serving Ben Hur TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $225.40.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Penelope_eng": [
    {"title": "Mini Excavator Rental Penelope TX — $200/Day Delivered", "description": "Compact excavator for rent in Penelope TX. Delivered to your job site in Hill County.\n\nGreat for trenching, grading, utility work, stump removal, and land clearing.\n\n$200/day. Delivery to Penelope: $227.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Penelope TX — Delivery Available", "description": "Need a compact excavator in Penelope? We haul it to your site.\n\n$200/day + $227.40 delivery to Penelope.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Penelope TX Excavator Rental — Trenching, Grading & Clearing", "description": "Compact excavator rental serving Penelope TX. Ideal for rural properties, fence lines, and drainage work.\n\n$200/day. Delivery: $227.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Penelope TX — $200/Day", "description": "Kubota compact excavator rental in Penelope TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $227.40.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Penelope TX — $200/Day Delivered to Site", "description": "Compact excavator available for Penelope TX and the surrounding Hill County area.\n\n$200/day + $227.40 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Penelope_eng": [
    {"title": "Track Loader Rental Penelope TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent in Penelope TX.\n\nIdeal for grading, clearing brush, loading material, and heavy site prep.\n\n$300/day. Delivery to Penelope: $227.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Penelope TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Penelope TX. Better traction than wheeled skid steers on rough terrain.\n\n$300/day. Penelope delivery: $227.40.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Penelope TX — $300/Day", "description": "Need a track loader in Penelope TX? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $227.40 delivery to Penelope.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Penelope TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader for rent in Penelope TX. Handles demanding terrain and heavy loads.\n\nDaily rate: $300. Delivery: $227.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Penelope TX — Delivered to Your Site", "description": "Compact track loader rental serving Penelope TX. Delivered and retrieved on your schedule.\n\n$300/day. Delivery: $227.40.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Aquilla_eng": [
    {"title": "Mini Excavator Rental Aquilla TX — $200/Day Delivered", "description": "Compact excavator for rent near Aquilla TX. Delivered to your property.\n\nPerfect for trenching, grading, utility work, drainage, and land clearing.\n\n$200/day. Delivery to Aquilla: $227.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Aquilla TX — Delivery Available", "description": "Kubota compact excavator available for Aquilla TX. We haul it to your site.\n\n$200/day + $227.80 delivery to Aquilla.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Aquilla TX Excavator Rental — Trenching & Land Clearing", "description": "Compact excavator rental in Aquilla TX. Handles rural lots, fence lines, and utility work with ease.\n\n$200/day. Delivery: $227.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Aquilla TX — $200/Day", "description": "Kubota compact excavator rental serving Aquilla TX. Delivered and picked up from your site.\n\nRate: $200/day. Delivery: $227.80.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Aquilla TX — $200/Day Delivered to Site", "description": "Compact excavator available for Aquilla TX and surrounding Hill County areas.\n\n$200/day + $227.80 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Aquilla_eng": [
    {"title": "Track Loader Rental Aquilla TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Aquilla TX.\n\nGreat for grading, clearing, loading, and heavy site work in Hill County.\n\n$300/day. Delivery to Aquilla: $227.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Aquilla TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Aquilla TX. More traction than wheeled skid steers on rough or soft terrain.\n\n$300/day. Aquilla delivery: $227.80.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Aquilla TX — $300/Day", "description": "Need a track loader near Aquilla? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $227.80 delivery to Aquilla.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Aquilla TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Aquilla TX. Handles tough terrain and heavy loads.\n\nDaily rate: $300. Delivery: $227.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Aquilla TX — Delivered to Site", "description": "Compact track loader rental serving Aquilla TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $227.80.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ]
}
with open("data/batch_temp.json", "w") as f:
    json.dump(batch12, f, indent=2)
print(f"Written {len(batch12)} slots to batch_temp.json")
