import json
batch13 = {
  "mini-ex_Kirk_eng": [
    {"title": "Mini Excavator Rental Kirk TX — $200/Day Delivered", "description": "Compact excavator for rent near Kirk TX. Delivered to your job site.\n\nGreat for trenching, grading, utility lines, stump removal, and land clearing.\n\n$200/day. Delivery to Kirk: $228.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Kirk TX — Delivery Available", "description": "Kubota compact excavator available for Kirk TX. We haul it to your site.\n\n$200/day + $228.60 delivery to Kirk.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Kirk TX Excavator Rental — Trenching, Grading & More", "description": "Compact excavator rental in Kirk TX. Ideal for rural lot work, fence lines, and light construction.\n\n$200/day. Delivery: $228.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Kirk TX — $200/Day", "description": "Kubota compact excavator rental serving Kirk TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $228.60.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Kirk TX — $200/Day Delivered to Site", "description": "Compact excavator available for Kirk TX and surrounding areas.\n\n$200/day + $228.60 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Kirk_eng": [
    {"title": "Track Loader Rental Kirk TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Kirk TX.\n\nIdeal for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Kirk: $228.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Kirk TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Kirk TX. More traction than wheeled skid steers on rough terrain.\n\n$300/day. Kirk delivery: $228.60.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Kirk TX — $300/Day", "description": "Need a track loader near Kirk TX? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $228.60 delivery to Kirk.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Kirk TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Kirk TX. Handles tough terrain and heavy loads.\n\nDaily rate: $300. Delivery: $228.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Kirk TX — Delivered to Site", "description": "Compact track loader rental serving Kirk TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $228.60.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Westphalia_eng": [
    {"title": "Mini Excavator Rental Westphalia TX — $200/Day Delivered", "description": "Compact excavator for rent near Westphalia TX. Delivered to your job site in Falls County.\n\nPerfect for trenching, grading, drainage, stump removal, and land clearing.\n\n$200/day. Delivery to Westphalia: $229.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator Rental Near Westphalia TX — Delivery Available", "description": "Need a compact excavator in Westphalia? We bring the machine to you.\n\n$200/day + $229.00 delivery to Westphalia.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Westphalia TX Excavator Rental — Trenching & Land Clearing", "description": "Compact excavator rental serving Westphalia TX. Handles rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $229.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Westphalia TX — $200/Day", "description": "Kubota compact excavator rental in Westphalia TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $229.00.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Westphalia TX — $200/Day Delivered to Site", "description": "Compact excavator available for Westphalia TX and the surrounding Falls County area.\n\n$200/day + $229.00 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Westphalia_eng": [
    {"title": "Track Loader Rental Westphalia TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Westphalia TX.\n\nGreat for grading, clearing brush, loading, and construction site work.\n\n$300/day. Delivery to Westphalia: $229.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Westphalia TX — Rent Daily", "description": "Kubota SVL75-2 track loader rental in Westphalia TX. Stable on rough or soft terrain.\n\n$300/day. Westphalia delivery: $229.00.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Westphalia TX — $300/Day", "description": "Need a track loader near Westphalia? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $229.00 delivery to Westphalia.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Westphalia TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Westphalia TX. Handles demanding ground and heavy loads.\n\nDaily rate: $300. Delivery: $229.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Westphalia TX — Delivered to Site", "description": "Compact track loader rental serving Westphalia TX. Delivered and retrieved on your schedule.\n\n$300/day. Delivery: $229.00.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Travis_eng": [
    {"title": "Mini Excavator Rental Travis TX — $200/Day Delivered", "description": "Compact excavator for rent near Travis TX. Delivered to your property.\n\nIdeal for trenching, grading, utility lines, stump removal, and land clearing.\n\n$200/day. Delivery to Travis: $229.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Travis TX — Delivery Available", "description": "Kubota compact excavator available for Travis TX. We haul it to your site.\n\n$200/day + $229.80 delivery to Travis.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Travis TX Excavator Rental — Trenching, Grading & Clearing", "description": "Compact excavator rental in Travis TX. Ideal for rural lots, fence lines, and drainage projects.\n\n$200/day. Delivery: $229.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Travis TX — $200/Day", "description": "Kubota compact excavator rental serving Travis TX. Delivered and picked up from your site.\n\nRate: $200/day. Delivery: $229.80.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Travis TX — $200/Day Delivered to Site", "description": "Compact excavator available for Travis TX and nearby areas.\n\n$200/day + $229.80 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Travis_eng": [
    {"title": "Track Loader Rental Travis TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Travis TX.\n\nPerfect for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Travis: $229.80.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Travis TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Travis TX. Stable and powerful on rough terrain.\n\n$300/day. Travis delivery: $229.80.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Travis TX — $300/Day", "description": "Need a track loader near Travis TX? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $229.80 delivery to Travis.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Travis TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Travis TX. Handles tough terrain and heavy loads.\n\nDaily rate: $300. Delivery: $229.80.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Travis TX — Delivered to Site", "description": "Compact track loader rental serving Travis TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $229.80.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Tyson_eng": [
    {"title": "Mini Excavator Rental Tyson TX — $200/Day Delivered", "description": "Compact excavator for rent near Tyson TX. Delivered to your job site.\n\nGreat for trenching, grading, utility work, stump removal, and drainage.\n\n$200/day. Delivery to Tyson: $230.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Tyson TX — Delivery Available", "description": "Kubota compact excavator available for Tyson TX. We bring the machine to you.\n\n$200/day + $230.20 delivery to Tyson.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Tyson TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in Tyson TX. Ideal for rural lot work and light construction.\n\n$200/day. Delivery: $230.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Tyson TX — $200/Day", "description": "Kubota compact excavator rental serving Tyson TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $230.20.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Tyson TX — $200/Day Delivered to Site", "description": "Compact excavator available for Tyson TX and surrounding areas.\n\n$200/day + $230.20 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Tyson_eng": [
    {"title": "Track Loader Rental Tyson TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Tyson TX.\n\nIdeal for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Tyson: $230.20.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Tyson TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Tyson TX. More traction than wheeled skid steers on rough terrain.\n\n$300/day. Tyson delivery: $230.20.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Tyson TX — $300/Day", "description": "Need a track loader near Tyson? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $230.20 delivery to Tyson.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Tyson TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Tyson TX. Handles tough ground conditions and heavy loads.\n\nDaily rate: $300. Delivery: $230.20.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Tyson TX — Delivered to Site", "description": "Compact track loader rental serving Tyson TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $230.20.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Laguna Park_eng": [
    {"title": "Mini Excavator Rental Laguna Park TX — $200/Day Delivered", "description": "Compact excavator for rent in Laguna Park TX. Delivered to your job site on Lake Whitney.\n\nPerfect for trenching, grading, drainage, stump removal, and land clearing.\n\n$200/day. Delivery to Laguna Park: $230.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator Rental Near Laguna Park TX — Delivery Available", "description": "Need a compact excavator in Laguna Park? We bring the machine to you.\n\n$200/day + $230.60 delivery to Laguna Park.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Laguna Park TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental serving Laguna Park TX. Great for lakefront property work, lot clearing, and utility digging.\n\n$200/day. Delivery: $230.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Laguna Park TX — $200/Day", "description": "Kubota compact excavator rental in Laguna Park TX. Delivered and picked up from your site.\n\nRate: $200/day. Delivery: $230.60.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Laguna Park TX — $200/Day Delivered to Site", "description": "Compact excavator available for Laguna Park TX and the Lake Whitney area.\n\n$200/day + $230.60 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Laguna Park_eng": [
    {"title": "Track Loader Rental Laguna Park TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent in Laguna Park TX.\n\nGreat for grading, clearing, loading, and site work in the Lake Whitney area.\n\n$300/day. Delivery to Laguna Park: $230.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Laguna Park TX — Rent Daily", "description": "Kubota SVL75-2 track loader rental in Laguna Park TX. Handles soft or uneven lakeside terrain well.\n\n$300/day. Laguna Park delivery: $230.60.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Laguna Park TX — $300/Day", "description": "Need a track loader in Laguna Park TX? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $230.60 delivery to Laguna Park.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Laguna Park TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader for rent in Laguna Park TX. Powerful and stable for demanding site conditions.\n\nDaily rate: $300. Delivery: $230.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Laguna Park TX — Delivered to Site", "description": "Compact track loader rental serving Laguna Park TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $230.60.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Rogers_eng": [
    {"title": "Mini Excavator Rental Rogers TX — $200/Day Delivered", "description": "Compact excavator for rent in Rogers TX. Delivered to your job site in Bell County.\n\nGreat for trenching, drainage, grading, stump removal, and land clearing.\n\n$200/day. Delivery to Rogers: $231.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent in Rogers TX — Delivery Available", "description": "Need a compact excavator in Rogers? We bring the machine to you.\n\n$200/day + $231.40 delivery to Rogers.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rogers TX Excavator Rental — Trenching, Grading & Clearing", "description": "Compact excavator rental serving Rogers TX. Ideal for residential and rural dig work across Bell County.\n\n$200/day. Delivery: $231.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Rogers TX — $200/Day", "description": "Kubota compact excavator rental in Rogers TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $231.40.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Rogers TX — $200/Day Delivered to Site", "description": "Compact excavator available for Rogers TX and the surrounding Bell County area.\n\n$200/day + $231.40 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Rogers_eng": [
    {"title": "Track Loader Rental Rogers TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent in Rogers TX.\n\nPerfect for grading, clearing, loading, and heavy site work in Bell County.\n\n$300/day. Delivery to Rogers: $231.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader in Rogers TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental serving Rogers TX. Stable and powerful on rough terrain.\n\n$300/day. Rogers delivery: $231.40.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Rogers TX — $300/Day", "description": "Renting the Kubota SVL75-2 track loader to Rogers TX. We deliver and pick up.\n\n$300/day + $231.40 delivery to Rogers.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rogers TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader for rent in Rogers TX. Handles demanding terrain and heavy loads.\n\nDaily rate: $300. Delivery: $231.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Rogers TX — Delivered to Your Site", "description": "Compact track loader rental serving Rogers TX. Delivered and retrieved on your schedule.\n\n$300/day. Delivery: $231.40.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Barclay_eng": [
    {"title": "Mini Excavator Rental Barclay TX — $200/Day Delivered", "description": "Compact excavator for rent near Barclay TX. Delivered to your job site.\n\nIdeal for trenching, grading, utility work, stump removal, and land clearing.\n\n$200/day. Delivery to Barclay: $232.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Barclay TX — Delivery Available", "description": "Kubota compact excavator available for Barclay TX. We haul it to your site.\n\n$200/day + $232.60 delivery to Barclay.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Barclay TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in Barclay TX. Perfect for rural lot work and light construction.\n\n$200/day. Delivery: $232.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Barclay TX — $200/Day", "description": "Kubota compact excavator rental serving Barclay TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $232.60.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Barclay TX — $200/Day Delivered to Site", "description": "Compact excavator available for Barclay TX and surrounding areas.\n\n$200/day + $232.60 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Barclay_eng": [
    {"title": "Track Loader Rental Barclay TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Barclay TX.\n\nGreat for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Barclay: $232.60.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Barclay TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Barclay TX. More traction than wheeled skid steers on rough terrain.\n\n$300/day. Barclay delivery: $232.60.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Barclay TX — $300/Day", "description": "Need a track loader near Barclay TX? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $232.60 delivery to Barclay.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Barclay TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Barclay TX. Handles tough ground conditions and heavy loads.\n\nDaily rate: $300. Delivery: $232.60.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Barclay TX — Delivered to Site", "description": "Compact track loader rental serving Barclay TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $232.60.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Leedale_eng": [
    {"title": "Mini Excavator Rental Leedale TX — $200/Day Delivered", "description": "Compact excavator for rent near Leedale TX. Delivered to your property.\n\nPerfect for trenching, grading, drainage, stump removal, and land clearing.\n\n$200/day. Delivery to Leedale: $233.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Leedale TX — Delivery Available", "description": "Kubota compact excavator available for Leedale TX. We bring the machine to you.\n\n$200/day + $233.40 delivery to Leedale.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Leedale TX Excavator Rental — Trenching & Land Clearing", "description": "Compact excavator rental in Leedale TX. Handles rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $233.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Leedale TX — $200/Day", "description": "Kubota compact excavator rental serving Leedale TX. Delivered and picked up from your site.\n\nRate: $200/day. Delivery: $233.40.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Leedale TX — $200/Day Delivered to Site", "description": "Compact excavator available for Leedale TX and nearby areas.\n\n$200/day + $233.40 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Leedale_eng": [
    {"title": "Track Loader Rental Leedale TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Leedale TX.\n\nIdeal for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Leedale: $233.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Leedale TX — Rent Daily", "description": "Kubota SVL75-2 track loader rental in Leedale TX. Stable on rough and soft terrain.\n\n$300/day. Leedale delivery: $233.40.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Leedale TX — $300/Day", "description": "Need a track loader near Leedale? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $233.40 delivery to Leedale.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Leedale TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Leedale TX. Handles demanding terrain and heavy loads.\n\nDaily rate: $300. Delivery: $233.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Leedale TX — Delivered to Site", "description": "Compact track loader rental serving Leedale TX. Delivered and retrieved on your timeline.\n\n$300/day. Delivery: $233.40.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Lavender_eng": [
    {"title": "Mini Excavator Rental Lavender TX — $200/Day Delivered", "description": "Compact excavator for rent near Lavender TX. Delivered to your job site.\n\nGreat for trenching, grading, utility lines, stump removal, and land clearing.\n\n$200/day. Delivery to Lavender: $233.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Lavender TX — Delivery Available", "description": "Kubota compact excavator available for Lavender TX. We haul it to your site.\n\n$200/day + $233.40 delivery to Lavender.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Lavender TX Excavator Rental — Trenching & Grading", "description": "Compact excavator rental in Lavender TX. Ideal for rural lot work and light construction projects.\n\n$200/day. Delivery: $233.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Lavender TX — $200/Day", "description": "Kubota compact excavator rental serving Lavender TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $233.40.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Lavender TX — $200/Day Delivered to Site", "description": "Compact excavator available for Lavender TX and surrounding areas.\n\n$200/day + $233.40 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Lavender_eng": [
    {"title": "Track Loader Rental Lavender TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Lavender TX.\n\nPerfect for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Lavender: $233.40.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Lavender TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Lavender TX. More traction than wheeled machines on rough terrain.\n\n$300/day. Lavender delivery: $233.40.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Lavender TX — $300/Day", "description": "Need a track loader near Lavender TX? We deliver the Kubota SVL75-2 to you.\n\n$300/day + $233.40 delivery to Lavender.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Lavender TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Lavender TX. Handles tough terrain and heavy loads.\n\nDaily rate: $300. Delivery: $233.40.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Lavender TX — Delivered to Site", "description": "Compact track loader rental serving Lavender TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $233.40.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "mini-ex_Frosa_eng": [
    {"title": "Mini Excavator Rental Frosa TX — $200/Day Delivered", "description": "Compact excavator for rent near Frosa TX. Delivered to your job site.\n\nGreat for trenching, grading, drainage, stump removal, and land clearing.\n\n$200/day. Delivery to Frosa: $237.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Excavator for Rent Near Frosa TX — Delivery Available", "description": "Kubota compact excavator available for Frosa TX. We bring the machine to you.\n\n$200/day + $237.00 delivery to Frosa.\n\n📞 254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Frosa TX Excavator Rental — Trenching & Land Clearing", "description": "Compact excavator rental in Frosa TX. Handles rural lots, fence lines, and utility work.\n\n$200/day. Delivery: $237.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Rent a Mini-Ex in Frosa TX — $200/Day", "description": "Kubota compact excavator rental serving Frosa TX. Delivered and picked up from your property.\n\nRate: $200/day. Delivery: $237.00.\n\n254.655.3339 | 5510 Old Lorena Rd, Lorena TX\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Mini Excavator — Frosa TX — $200/Day Delivered to Site", "description": "Compact excavator available for Frosa TX and surrounding areas.\n\n$200/day + $237.00 delivery.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ],
  "trackloader_Frosa_eng": [
    {"title": "Track Loader Rental Frosa TX — $300/Day Delivered", "description": "Kubota SVL75-2 compact track loader for rent near Frosa TX.\n\nIdeal for grading, clearing, loading, and heavy site work.\n\n$300/day. Delivery to Frosa: $237.00.\n\n📍 5510 Old Lorena Road, Lorena TX 76655\n📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Skid Steer Track Loader Near Frosa TX — Rent by the Day", "description": "Kubota SVL75-2 track loader rental in Frosa TX. More traction than wheeled skid steers on rough terrain.\n\n$300/day. Frosa delivery: $237.00.\n\n📍 Lorena TX 76655 | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Compact Track Loader for Rent — Frosa TX — $300/Day", "description": "Need a track loader near Frosa? We deliver the Kubota SVL75-2 to your site.\n\n$300/day + $237.00 delivery to Frosa.\n\n254.655.3339 | Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "Frosa TX Track Loader Rental — Kubota SVL75-2", "description": "SVL75-2 track loader rental near Frosa TX. Handles tough ground conditions and heavy loads.\n\nDaily rate: $300. Delivery: $237.00.\n\n📍 5510 Old Lorena Rd, Lorena TX | 📞 254.655.3339\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."},
    {"title": "SVL75-2 Track Loader — Frosa TX — Delivered to Site", "description": "Compact track loader rental serving Frosa TX. Delivered and picked up on your schedule.\n\n$300/day. Delivery: $237.00.\n\n📞 254.655.3339 | 📍 Lorena TX 76655\n💳 Zelle · Venmo · Cash App · PayPal · Check · Cash\n\nAsk about multi-day rates."}
  ]
}
with open("data/batch_temp.json", "w") as f:
    json.dump(batch13, f, indent=2)
print(f"Written {len(batch13)} slots to batch_temp.json")
